### ISSUE TITLE
Add a better description to AMO

### ISSUE THREAD

**Issue by evilpie** [nt1m/livemarks#10]
A lot of people seem to be unaware that you can enable read/unread prefixes. Maybe even make that the default?

**Comment by evilpie** [comment]
I updated the description on AMO a bit

**Comment by nt1m** [comment]
@evilpie Read/unread prefixes is a hidden and unexposed feature.

**Comment by evilpie** [comment]
Yeah let's forget about read/unread for now. I hope the new description on AMO is ok.
