### ISSUE TITLE
problem with feed burner: can't load feed 

### ISSUE THREAD

**Issue by ExXeptional** [nt1m/livemarks#101]
I'm had problems adding this feed to livemarks: http://feeds.feedburner.com/AvasDemon
It said: "Failed to fetch feed"

I then disabled tracking protection and uBlockOrigin on the feedburner site, reloaded it and clicked on this now visible link:

![grafik](https://user-images.githubusercontent.com/40037381/50035900-04fc7080-0005-11e9-86c8-61f79c460582.png)

it points to: http://feeds.feedburner.com/AvasDemon?format=xml

then it automatically opened the livemarks page and I could subscribe to the feed
just fyi, maybe add it to FAQ 
(or add the "?format=xml" automatically to feedburner links, if thats possible somehow)

**Comment by evilpie** [comment]
I can't reproduce this, http://feeds.feedburner.com/AvasDemon works for me. I actually explicityl tested feedburner before.

**Comment by evilpie** [comment]
Btw http://feeds.feedburner.com/AvasDemon should already render our own preview page, so I am not sure why you even see the other one.

**Comment by ExXeptional** [comment]
It works now for me, too.
Sorry, maybe this was a one time thing.
