### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by megamarw1** [nt1m/livemarks#111]
The idea is really great and I can do everything I should be able to (I can preview a feed, I can subscribe, I can change settings), but the actual livemarks don't appear at all. No manual refresh and no auto refresh work.

**Comment by evilpie** [comment]
@megamarw1 hey do you still have this issue?

**Comment by megamarw1** [comment]
Hi. Sorry die replying so late, but I was not home for a week. 
No I don’t, it seemes it was a problem with the xml file containing the feed. I reinstalled the feed-generator and it worked. Thanks for the help.
