### ISSUE TITLE
Removed from AMO?

### ISSUE THREAD

**Issue by yoasif** [nt1m/livemarks#113]
"Page not found" when navigating to https://addons.mozilla.org/en-US/firefox/addon/livemarks/

**Comment by Hoppaz** [comment]
same problem here

**Comment by T3rm1** [comment]
Maybe they want users to switch to another browser.

**Comment by nunovieira** [comment]
Just started using this morning and now it disappeared?
I'm very frustrated with the removal of Live Bookmarks! This looks like the worse decision Mozilla ever made! They should restore that functionality, ASAP!
I commend the developers of this project for their effort, but this should be a basic Firefox feature. If it was based on old code, it should be improved.
The worse thing is, there is no good alternative. Firefox was the alternative. Now it's becoming crap like all others.

**Comment by nt1m** [comment]
It failed AMO review for 2 issues, @evilpie already submitted a new version and I just pinged the reviewers privately so it can be back up as fast as possible.

**Comment by evilpie** [comment]
Thanks for reaching out. The issues turned out to be minor or some misunderstanding. The AMO admins have been incredibly responsive in solving this issue and it's now available again.
