### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by olivier-voutat** [nt1m/livemarks#114]
I have a feed that take some time to respond, so I'm always having a timeout in the plugin....

**Comment by nt1m** [comment]
@evilpie Should we increase the XHR timeout ?

**Comment by olivier-voutat** [comment]
or allow edition in configuration.

**Comment by evilpie** [comment]
We can change it to 10seconds, but wow that is one slow feed.

**Comment by olivier-voutat** [comment]
Big database check...

**Comment by olivier-voutat** [comment]
It works better. Thank you.
