### ISSUE TITLE
High CPU usage after last update

### ISSUE THREAD

**Issue by mattcoz** [nt1m/livemarks#119]
Getting very high CPU usage after the most recent update. I'm able to confirm that it is this addon causing it. I disable it and the high CPU usage goes away. I enable it again and the high CPU usage returns.

**Comment by evilpie** [comment]
Please provide more information, so we can help you debug this. The OPML export of your feed would be helpful. Were you actively visiting feed items etc.

Can you try disabling the read/unread feature? Just go to settings, an remove all bookmark prefixes (✓). Disable and enable the extension in about:addons.

Thanks

**Comment by mattcoz** [comment]
I was doing nothing. I can't even get to the settings to change anything. I did disable and enable the extension as I previously mentioned.

**Comment by mattcoz** [comment]
Ok, here's a clue. Lots of errors in the browser console. One of my feeds is timing out and another is getting a bad xml error. Unfortunately I can't get to the settings to change or remove these feeds.

**Comment by nt1m** [comment]
@mattcoz Does the latest version (1.14) solve the CPU issues ?

**Comment by mattcoz** [comment]
Ok, the one timeout stopped, must have been a server issue. But the other keeps failing. I deleted the bookmark and now I just get this error over and over: Found broken bookmark 8LGqfUns75Ko <unavailable>.

**Comment by mattcoz** [comment]
How do I get 1.14?

**Comment by nt1m** [comment]
@mattcoz It's just been approved a minute ago, you should be able to receive the update now.

**Comment by mattcoz** [comment]
Got it, yes it does!
