### ISSUE TITLE
Some feeds show subfolders instead of the article links

### ISSUE THREAD

**Issue by rcmcronny** [nt1m/livemarks#12]
Screenshot from the heise.de Feed on my Firefox stable (61.0.1) installation:
![index](https://user-images.githubusercontent.com/5807210/43676593-89628d42-97f4-11e8-89e9-a3c0410af3cf.png)

FeedURL: https://www.heise.de/newsticker/heise-atom.xml
Some Feeds are ok, some feeds, show that behavior and i can not click them to open the article, is this already known ?

**Comment by evilpie** [comment]
This should be fixed by #8.

**Comment by rcmcronny** [comment]
👍 
sorry missed that closed  issue, when do you plan to release an update :) ?

**Comment by nt1m** [comment]
@rcmcronny I'd like to fix a couple more issues before releasing an update.

**Comment by Darkspirit** [comment]
This was the most noticiable bug for me, so the extension had no practical function.

**Comment by nt1m** [comment]
@Darkspirit @rcmcronny I published an update fixing this!
