### ISSUE TITLE
Handle relative URLs properly in extension

### ISSUE THREAD

**Issue by svarogg** [nt1m/livemarks#120]
If I try to subscribe to most feeds (tryed both RSS and atom), it usually works, but for some reason the Golang blog is a different story:
https://blog.golang.org/feeds/posts/default

Livemark seemingly can parse the feed, because it does gets opened using the Livemark stylesheet, etc.

However, after clicking "+ Add Livemark", the folder is always empty.

In the addon debug log I see: Invalid bookmark: {"title":"Open \"The Go Programming Language Blog\"","type":1,"url":"//blog.golang.org/modules2019","parentGuid":"GGcb2C16bi5v"}

Quick note: the same feed worked with no problem in Firefox Live Bookmarks, before they were disabled.

**Comment by nt1m** [comment]
Ah, the siteUrl of that blog starts with `//` instead of `https://`. I guess we should handle this case too.
