### ISSUE TITLE
Only loading 25 bookmarks? 

### ISSUE THREAD

**Issue by fsstr** [nt1m/livemarks#122]
Is it possible to get livemarks to include an entire RSS feed?  I only seem to get the first 25.

**Comment by nt1m** [comment]
@fsstr You can change the "Max Items" setting for your feed.

**Comment by nt1m** [comment]
Closing as you can change the "Max Items" to a very large value.

**Comment by fsstr** [comment]
I got it, I was looking in the wrong place. :)

Sorry if I am reopening this issue, but just wanted to say thank you!
