### ISSUE TITLE
Localization fix ups

### ISSUE THREAD

**Issue by nt1m** [nt1m/livemarks#129]
Unlocalized items:

- [x] Reload livemark menu item

- [x] Setup Transifex style system to contribute translations 
- [x] Update "Contributing Translations" link in the add-on

**Comment by nt1m** [comment]
I don't think there's anything else to do here, please let me know if I missed any strings though.

**Comment by piotrdrag** [comment]
Could you please accept me on Transifex?

**Comment by nt1m** [comment]
@piotrdrag Done! :) Thanks for your help!
