### ISSUE TITLE
Issue with non-utf8 encoded feeds

### ISSUE THREAD

**Issue by evilpie** [nt1m/livemarks#13]
_(Seen in an AMO review)_
This [feed](https://rss.golem.de/rss.php?feed=RSS1.0) uses the ISO-8859-1 encoding, which produces display errors. I am not sure how to fix this with fetch and DOMParser. I have an alternative implementation that uses XMLHttpRequest, which would handle the encoding for us.

**Comment by nt1m** [comment]
Do you have some sample code that does this using XMLHttpRequest ? Thanks!
