### ISSUE TITLE
Feed items with no <title> tag display "null"

### ISSUE THREAD

**Issue by t-kazi** [nt1m/livemarks#138]
https://backcomic.com/rss.xml

^ I am subscribed to this comic. The original `LiveBookmarks` displayed the comic link (probably just from the `<link>` tag). This particular RSS XML is missing the `<title>` tag. I think because of that, the LiveMarks addon just lists a bunch of `null` titles.

**LiveBookmarks**
<img width="247" alt="tk_screen shot 2019-01-04 at 12 28 36 pm" src="https://user-images.githubusercontent.com/1698481/50704276-720b9080-101c-11e9-8264-bee1d510b164.png">

**LiveMarks addon**
<img width="464" alt="tk_screen shot 2019-01-04 at 12 25 43 pm" src="https://user-images.githubusercontent.com/1698481/50704143-f1e52b00-101b-11e9-850c-de90dd6c03fa.png">

**Comment by tanzeelkazi** [comment]
Thank you for the quick fix! Hope it will be released soon.
