### ISSUE TITLE
Firefox using 100% CPU and livemarks not updating

### ISSUE THREAD

**Issue by ali1234** [nt1m/livemarks#148]
**Add-on version**
Add-on version: 1.16

**Describe the bug**
Firefox starts using 100% CPU. Livemarks don't update and you can't create new ones. Clicking a livemark doesn't add the tick for seen items. When I exit Firefox it keeps running for a long time and won't let me open a new window. Eventually it shows the crash dialog (I will try to get the error report next time, but it doesn't seem to contain anything related to Livemarks). After I restart it the livemarks start updating again. I have been on Firefox 64 and Livemarks 1.16 for a while but this only started happening about a week ago. It could be some other extension messing up but I haven't installed any new ones recently. Nothing else seems to stop working when it happens.

**To Reproduce**
Leave Firefox running for a couple of days.

**Comment by nt1m** [comment]
Does about:performance explicitely show Livemarks as responsible ?

**Comment by ali1234** [comment]
about:performance doesn't show anything out of the ordinary (but it never does)

**Comment by ali1234** [comment]
I can't add, delete, or modify any bookmark anywhere in firefox. Not by right clicking/drag and drop in the menus, not through the bookmark editor, not with ctrl-D.

I suspect the bookmark database is stuck, probably due to a race condition when deleting bookmarks. Since it is some kind of RPC this manifests as message spam. Sync is probably involved too somehow.

I didn't keep the profiler trace but I can make another one if you want. I doubt it will show anything though.

**Comment by ali1234** [comment]
Just tried "Places integrity test" in about:support and it says this:

```
> Task: checkIntegrity
- Unable to check favicons.sqlite integrity: Error: Could not open connection to /home/al/.mozilla/firefox/o65awu5u.default-1503600779742/favicons.sqlite: 2153971713
> Task: invalidateCaches
- The task queue was cleared by an error in another task.
> Task: checkCoherence
- The task queue was cleared by an error in another task.
> Task: expire
- The task queue was cleared by an error in another task.
> Task: originFrecencyStats
- The task queue was cleared by an error in another task.
> Task: vacuum
- The task queue was cleared by an error in another task.
> Task: stats
- The task queue was cleared by an error in another task.
> Task: _refreshUI
- The task queue was cleared by an error in another task.
```

lsof on that database file shows firefox has already opened it five times:

```
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
firefox 16225   xx   79ur  REG   8,18 74088448 29235169 /home/al/.mozilla/firefox/o65awu5u.default-1503600779742/favicons.sqlite
firefox 16225   xx   86rr  REG   8,18 74088448 29235169 /home/al/.mozilla/firefox/o65awu5u.default-1503600779742/favicons.sqlite
firefox 16225   xx  148rr  REG   8,18 74088448 29235169 /home/al/.mozilla/firefox/o65awu5u.default-1503600779742/favicons.sqlite
firefox 16225   xx  165rr  REG   8,18 74088448 29235169 /home/al/.mozilla/firefox/o65awu5u.default-1503600779742/favicons.sqlite
firefox 16225   xx  240ur  REG   8,18 74088448 29235169 /home/al/.mozilla/firefox/o65awu5u.default-1503600779742/favicons.sqlite
```

**Comment by ali1234** [comment]
2153971713 = 0x80630001 (NS_ERROR_STORAGE_BUSY)

**Comment by ali1234** [comment]
I submitted a crash report to Mozilla and it found this bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=1326309

**Comment by ali1234** [comment]
I haven't had this happen again since my last post. I suspect either upgrading to 65 or simply turning bookmark sync off and then on again fixed the problem somehow.
