### ISSUE TITLE
Add a reset button

### ISSUE THREAD

**Issue by nt1m** [nt1m/livemarks#149]
Given the issues with `browser.storage.sync` preventing the user completely from interacting with the add-on, it would be nice to add a reset button to the settings page.

I'll look into this in February if no one does before me.

**Comment by evilpie** [comment]
We discussed this briefly. I believe in most cases the underlying storage is actually corrupt so a reset button won't help much.

**Comment by nt1m** [comment]
There's an underlying Firefox bug to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1524698

Going to close this :)
