### ISSUE TITLE
All livemarks feed are empty after firefox 65.0 update

### ISSUE THREAD

**Issue by vormav78** [nt1m/livemarks#151]
I had to recreate all of my feeds and now they're ok. Just letting people know.

**Comment by evilpie** [comment]
@vormav78 Is it possible that with version 1.17, they show up as "Broken bookmarks" in the options?

**Comment by vormav78** [comment]
No, they all looked fine in the options. They each had a Name, Feed URL and Site URL. In fact I just re-used all the information when creating new ones and the new ones worked.

**Comment by evilpie** [comment]
If you already recreated your livemarks there isn't much we can do now to debug this. Closing.

**Comment by vormav78** [comment]
Yeah, I didn't need help debugging really. My goal was more to warn people that this can happen.
