### ISSUE TITLE
hidden hijacker?

### ISSUE THREAD

**Issue by manebule** [nt1m/livemarks#152]
**Add-on version**
Add-on version: 1.15? I don't know for sure--I just removed it...

**Describe the bug**
A number of times--perhaps ten in the past couple of weeks--I have clicked on my 'livemarks' folders and gotten a redirect with a tab title something like "2019 Annual Visitor Survey" and a "Dear Firefox User, You are today's lucky visitor..." message asking me to complete a survey (see attached photo). It all looks very suspicious... Malwarebytes reported a 'hijack' on one of the redirects. I'd be happy to submit the report if that would help. Other than that, Malwarebytes and MSSE both report that the computer is clean. I'm posting here because it only happens when I click on a 'livemarks' folder (which I use for BBC and CBC [Canada] news), and that only randomly.

**To Reproduce**
1. click 'livemarks' folder (Firefox 64.0.2 64-bit)
2. see redirect webpage [NB 'livemarks' folder doesn't even open}

**Expected behavior**
'livemarks' folder would open; new tab wouldn't open

**Extra context**
![livemarks redirect](https://user-images.githubusercontent.com/47201213/52029145-cc3a2d00-24c6-11e9-8e8c-d58937e8615d.png)

**Comment by nt1m** [comment]
Hi @manebule, it sounds like your network or a different application is interfering with your Firefox web activity. I would recommend checking the list of your installed programs on Windows and check if you see anything suspicious.

**Comment by nt1m** [comment]
Also, I recommend using this add-on: https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/ which blocks malicious advertising on the web.

**Comment by nt1m** [comment]
I've talked to some Mozilla employees, and they recommend reporting the survey URL to:  https://www.mozilla.org/en-US/about/legal/fraud-report/ 

This way, Mozilla can take legal action.

**Comment by nt1m** [comment]
What happens when you click the back button when on the redirected malware page ? It would be useful to figure out if your computer has been compromised, or if one of the webpages you've visited is affected.

**Comment by evilpie** [comment]
You might also want to read https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-caused-malware.

**Comment by nt1m** [comment]
I'm going to close this because there's nothing we can do on the add-on side. We'd be happy to look at any extra information you may have however.
