### ISSUE TITLE
More options button and (...) button very slow response

### ISSUE THREAD

**Issue by mysterixx** [nt1m/livemarks#153]
When I click In Preferences > More options it takes 10 seconds for dialog to appear. 

When I click (...) button on right side of each feed it takes 10 seconds for dilaog to appear. 

I am a heavy bookmark user and have thousands of bookmarks. Is it related to this or what is the bug here?

**Comment by ZeroCool940711** [comment]
Im having this exact problem too, clicking on More Options or the (...) takes a while to load, I even thought it was broken and not working but it was just too slow to load.

**Comment by ZeroCool940711** [comment]
Having this problem again on Firefox 67, for me its not only the More Options but also the `+Add Livemark` button when trying to add a new feed.
