### ISSUE TITLE
Use URL in <guid> element should be used when <link> element is absent

### ISSUE THREAD

**Issue by daitau** [nt1m/livemarks#157]
**Feed URL**
http://rthk9.rthk.hk/rthk/news/rss/e_expressnews_einternational.xml

**Add-on version**
Add-on version: 1.18

**Describe the bug**
The URL in &lt;guid&gt; element should be used if &lt;link&gt; is absent. I think that was the behaviour in the old Firefox live bookmarks implementation.

**To Reproduce**
1. Browse the live bookmark created using the above feed URL
2. Only the feed page is shown

**Expected behavior**
Individual pages for each item should open.

**Comment by nt1m** [comment]
Thanks for reporting this! I fixed the issue and it should be deployed in the next update.
