### ISSUE TITLE
[Feature request] Option to hide or change position of 'Open "[sitename]"' bookmark

### ISSUE THREAD

**Issue by PaulLFC** [nt1m/livemarks#163]
I recently started using Livemarks and it's excellent - great work on the extension. One thing I think may be useful would be an option to hide or change the position of the 'Open "[sitename]"' bookmark, which seems to be the first bookmark in each livemark folder (for example the option to have this be the bottom bookmark in the list, rather than the first).

Personally I use livemarks folders to keep up to date with deals, and the 'Open "[sitename]"' option is slightly distracting (although this isn't a huge issue by any means). The option to hide this or move it to the end of the list would be appreciated, hopefully this may be helpful for other users of the extension too.

**Comment by evilpie** [comment]
It's not obvious, but this can be done. Go to the Livemarks options page, click the three dots for your livemark and clear the "Site URL" field of all text.

**Comment by PaulLFC** [comment]
> 
> 
> It's not obvious, but this can be done. Go to the Livemarks options page, click the three dots for your livemark and clear the "Site URL" field of all text.

Fantastic, thank you. Just did this for all feeds and the "Open [site]" link has gone for all folders. Thanks again.
