### ISSUE TITLE
“Giving a good review” URL is hardcoded to en_US

### ISSUE THREAD

**Issue by piotrdrag** [nt1m/livemarks#164]
**Add-on version**
Add-on version: 1.20

**Describe the bug**
Clicking “Giving a good review” always opens AMO in English.

**To Reproduce**
1. Go to add-on preferences
2. Click on “More options”
3. Click on the “Giving a good review” button
4. `https://addons.mozilla.org/en-US/firefox/addon/livemarks/reviews/add/` opens

**Expected behavior**
`https://addons.mozilla.org/firefox/addon/livemarks/reviews/add/` opens, which redirects me to AMO in my locale (`https://addons.mozilla.org/pl/firefox/addon/livemarks/reviews/add/`).

**Comment by nt1m** [comment]
Thanks for reporting!
