### ISSUE TITLE
Feed menu is empty on a private browsing window

### ISSUE THREAD

**Issue by wesinator** [nt1m/livemarks#165]
**Add-on version**
1.20
Firefox 65.0.1 macOS

**Describe the bug**
The livemarks feed menu is blank in a private browsing window

**To Reproduce**
1. Private Browsing, https://blog.mozilla.org/
2. Open livemarks icon

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5124946/54242981-0bfc2780-44fd-11e9-99b1-9169ac699a2a.png">

**Expected behavior**
Feeds offered, or address bar icon is hidden

Normal window:
![image](https://user-images.githubusercontent.com/5124946/54243097-82992500-44fd-11e9-9643-7aa867ba0cff.png)

**Comment by nt1m** [comment]
This is due to `runtime.getBackgroundPage()` not working on private windows. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1329304
