### ISSUE TITLE
Not working in Firefox anymore

### ISSUE THREAD

**Issue by violetree** [nt1m/livemarks#170]
**Add-on version**
Add-on version: 1.21

**Describe the bug**
Livemarks could not be verified for use in Firefox and has been disabled
**To Reproduce**

**Expected behavior**

**Extra context**
Any extra context you may have about the bug (feed URLs, screenshots, etc.)

**Comment by nt1m** [comment]
This is a known issue with Firefox itself, see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by violetree** [comment]
Thank you
