### ISSUE TITLE
Feed problem: The Sixth Axis

### ISSUE THREAD

**Issue by lgretton** [nt1m/livemarks#172]
**Feed URL**
https://www.thesixthaxis.com/category/news/playstation-news/feed/

**Add-on version**
Add-on version: 1.21

**Describe the bug**
Feed is not parsed

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://www.thesixthaxis.com/category/news/playstation-news/feed/'

**Expected behavior**
Feed is parsed into news articles

**Comment by evilpie** [comment]
The XML feed is invalid because there is a space before `<?xml`

`
XML Parsing Error: XML or text declaration not at start of entity
Location: https://www.thesixthaxis.com/category/news/playstation-news/feed/
Line Number 3, Column 1
`

**Comment by lgretton** [comment]
Thanks - I didn't spot that. I'll contact the site maintainers.
