### ISSUE TITLE
Feed problem: Keyboard Corner

### ISSUE THREAD

**Issue by marczellm** [nt1m/livemarks#178]
**Feed URL**: http://forums.musicplayer.com/cache/rss18.xml

**Add-on version**: 1.21

**Describe the bug**
My livemark pointing to the above feed does not update.
If I try to remove and readd the livemark I get an error message saying: "Error: no XML data"

I viewed the request object in the debugger and even though the response mimetype is set by the server as "application/xml", the responseXML member is null. The response and responseText members do contain the XML feed.

**Comment by evilpie** [comment]
Invalid XML
`XML Parsing Error: not well-formed
Location: http://forums.musicplayer.com/cache/rss18.xml
Line Number 76, Column 40:`

**Comment by marczellm** [comment]
What XML validator did you use?

**Comment by evilpie** [comment]
This is from Firefox trying to parse that feed. You can see the error message when opening the Browser Console.

**Comment by marczellm** [comment]
Thanks. It's a bug with the forum software that generated the RSS.
