### ISSUE TITLE
"Import feeds" doesn't do anything if feeds already exist

### ISSUE THREAD

**Issue by Goldor0ck** [nt1m/livemarks#193]
**Add-on version**
Add-on version: 2.1

**Describe the bug**
Unable to load other feeds on top of existing ones

**To Reproduce**
1. Go to 'Options/More Options'
2. Click on 'Import Feeds'
3. Nothing happens

**Expected behavior**
A dialog to upload an XML file should open

**Extra context**
Behaviour is different of the case when FF become unresponsive.
Nothing happens, that's all
Note: Firefox Quantum 68.0.1 (64 bits) on Windows 10

**Comment by Gittyperson** [comment]
You seem to imply there's a way to make it work. I just installed Firefox and Livemarks as the first -and only- extension, but Import feeds does nothing. Cannot import.

**Comment by snitgary** [comment]
Just noticed this too, Import doesn't work with V2.1 and Firefox 68.0.1 (64-bit).

**Comment by Gittyperson** [comment]
As a workaround, I installed version 1.21. Import is working (still doing its thing) but it doesn't seem to retain my folder structure. I don't know if this is possible anyway.

**Comment by nt1m** [comment]
Thanks for reporting! I'll give it a look sometime today. 

@Gittyperson Thanks for finding that the feature works in v1.21! I must have broken something in v2. Unfortunately, it doesn't retain your folder structure since there's no reliable way to do this with the current extension APIs.

**Comment by nt1m** [comment]
@Gittyperson @Goldor0ck @snitgary It does work on my side. Do you mind sharing your OPML files ? It could be an issue with the extension not coping well with some strangely formatted OPML files or simply a performance issue (importing lots of feeds).

**Comment by Goldor0ck** [comment]
@nt1m Tim, you misunderstood what we meant. I don't even have a dialog box to input an OPML file. Just _nothing_ happens when you click on the button...
@Gittyperson Thanks for confirming I has worked. I hadn't noticed the updated version, but I know it did work, since I had used it...

**Comment by Goldor0ck** [comment]
@nt1m By the way, this (wrong) behaviour is exactly the same with pre-Quantum versions of Firefox. But I didn't bother to open a case, since it obviously not supported ;-)

**Comment by nt1m** [comment]
@Goldor0ck Could you please take a screenshot of the settings dialog ? I'm curious if this is due to the new 2 column layout.

**Comment by Goldor0ck** [comment]
@nt1m Here you are, Tim...
![LivemarksImport](https://user-images.githubusercontent.com/54020541/62920487-2f761780-bda6-11e9-8399-ce7c05a26dc2.png)

**Comment by shadowbitdev** [comment]
Hello @nt1m 

I encountered this issue today.

Could the problem be that you have the <input> tag inside a button?
https://stackoverflow.com/questions/33420402/file-input-field-inside-button-doesnt-work-in-firefox

FYI, I used FF Developer Tools to move the input tag outside the button, then re-applied the listener you have on it (moving the input dropped the original listener), and at that point it worked as expected and was able to import from a file.

**Comment by evilpie** [comment]
Yeah I can reproduce this. "Import feeds" doesn't react to clicks. I think we can replace the `<a>` element with:
```html
<input id="import-feeds" name="files[]" type="file" hidden>
<label for=data-i18n-text="settings_importExport_importFeeds">Import feeds</label>
```

**Comment by nt1m** [comment]
@shadowbitdev @Goldor0ck @Gittyperson @evilpie  I think I fixed this in version 2.2 by no longer making the settings dialog overflow to a third column (I was able to reproduce it myself by making it overflow).

Can someone double-check if version 2.2 works ? Thanks!

@evilpie I agree it would be a cleaner solution, but I'm concerned that dragging-and-dropping into the input would no longer work.

**Comment by Gittyperson** [comment]
It seems to work fine now, thank you.

**Comment by Goldor0ck** [comment]
I can confirm that it works well now, on both of my computers.
Thank you for your prompt actions
