### ISSUE TITLE
Can't re-add icon of the extention to the toolbar.

### ISSUE THREAD

**Issue by darth-biomech** [nt1m/livemarks#198]
**Add-on version**
Add-on version: 2.1
Firefox: 68.0.2 (64-bit)

**Describe the bug**
I accidentally clicked the icon of the extension away from the toolbar, now I can't return it there: it's nowhere to be found in the "customize..." mode.

**Comment by evilpie** [comment]
Do you mean the Address/URL bar instead of toolbar? Inside the addressbar click the three dots, right click on "Subscribe" and select "Add to Addressbar".

**Comment by darth-biomech** [comment]
Hm, I'm not sure anymore. No, I was talking about the extension icon that leads you directly to the extension settings where you can manage feeds and settings of the extention (/pages/settings/settings.html). Or did my brain farted a little and livemarks don't have such icon?

**Comment by evilpie** [comment]
This is called [browserAction](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction) and Livemarks never implemented that.
