### ISSUE TITLE
Feedburner feeds not updating

### ISSUE THREAD

**Issue by notonymous** [nt1m/livemarks#200]
**Add-on version**
2.2

**Describe the bug**
Since the beginning of July, none of my feeds hosted on Feedburner are updating --e.g.
https://feeds.feedburner.com/scitechdaily  (latest: 1-July-2019)
https://feeds.feedburner.com/rcrwireless/sLmV  (latest: 3-July-2019)
http://feeds.feedburner.com/IeeeSpectrumFullText  (latest: 3-July-2019)

No problem with any other (non-Feedburner) feeds.

**Extra context**
Firefox Dev Edition 69.0b15 (buildID 20190819184224)
UA: Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0

**Comment by ali1234** [comment]
This seems to be some weird server misconfiguration. If I click those links the server returns HTML but if I copy paste them it returns RSS. I don't understand why though.

**Comment by notonymous** [comment]
I think this "issue" can be closed. I returned from vacation, updated to a new version of Firefox (70) with a new profile, and the problem seems to be gone.

Currently using Firefox Dev Edition 70.0b8 (buildID 20190919164641) with Livemarks 2,2
