### ISSUE TITLE
Lag when loading when using a screenreader

### ISSUE THREAD

**Issue by tapper82** [nt1m/livemarks#205]
Hi I use Livemarks on Firefox Nightly Windows 10. I read the menus with my screen reader NVDA. When opening a feed it lags to update I have to press the down arrow key 2 or 3 times before I can here the first item in the list. This does not happen on Firefox builds in the past. It started about 5 weeks ago. Thanks for reading and thanks for a grate Addin. PS are we going to get a new release I see that there has bin a lot of commits since 1.8?

**Comment by tapper82** [comment]
I have solved this. I looked at my add-ons page in Firefox and found that I had some how installed Privacy Badger twice. I don't know how! I didn't even know you could install to of the same addon sorry for the noise.

**Comment by nt1m** [comment]
Thanks for reporting! Glad to hear that you've fixed it.

> PS are we going to get a new release I see that there has bin a lot of commits since 1.8?

The latest release is 2.2 and was released last month on AMO. Let me know if you're not getting the update though, maybe you've installed a beta and were stuck on it ? The latest version is here: https://addons.mozilla.org/en-US/firefox/addon/livemarks/
