### ISSUE TITLE
Can't delete broken feeds

### ISSUE THREAD

**Issue by lukecz81** [nt1m/livemarks#206]
I can't remove broken feeds - there is only option to assign folder
![1](https://user-images.githubusercontent.com/55767292/65575837-02a24c00-df71-11e9-900b-e68852b665ef.png)
In which file can I find list of these boomarks to delete them manually?

**Comment by tapper82** [comment]
Hi thanks for fixing this. When will we get a update?

**Comment by evilpie** [comment]
Fixed by #265
