### ISSUE TITLE
Daily MtG feed does not display list of articles

### ISSUE THREAD

**Issue by Mikaill** [nt1m/livemarks#209]
**Feed URL:**
https://magic.wizards.com/en/rss/rss.xml?tags=Daily%20MTG&lang=en

**Repro:**
Create an RSS folder for the specified URL, see it's empty with just the link to the page.

**Expected behavior:**
The feed should be displaying list of articles.

**Comment by evilpie** [comment]
This is basically a duplicate of #202. The RSS items use a relative path in `<link>`.

**Comment by evilpie** [comment]
>xml:base may be used to control how relative URIs are resolved.

https://validator.w3.org/feed/docs/atom.html

**Comment by nt1m** [comment]
Duplicate of #202
