### ISSUE TITLE
Livemarks stopped working, "Error: An unexpected error occurred"

### ISSUE THREAD

**Issue by rmader** [nt1m/livemarks#212]
**Add-on version**
Add-on version: 2.4
Firefox version: 70

**Describe the bug**
I set up a new profile and added some livemarks. A few days later (maybe after the 2.4 update) the livemarks stopped working, they are now usual folders. Adding new livemarks fails (clicking the button does nothing), with the following message in the console:
```
Error: An unexpected error occurred
```

No output in the browser console. Also tried the steps from https://github.com/nt1m/livemarks/issues/147#issuecomment-459803819 without success (same error message), but that was apparently a different issue.

**To Reproduce**
not yet known

**Comment by nt1m** [comment]
Does downgrading to an old version fix the problem: https://addons.mozilla.org/en-US/firefox/addon/livemarks/versions/ ? (You'll likely have to setup the livemarks again unfortunately if it does work)

**Comment by rmader** [comment]
Sorry for not coming back to this so long. The error still persists and downgrading the version to e.g. 2.3 does not fix the issue. But at least I found some more useful debug info in the browser console:
```
Cannot send function call result: other side closed connection (call data: ({path:"tabs.create", args:[{active:null, cookieStoreId:null, discarded:null, index:null, openInReaderMode:null, openerTabId:null, pinned:null, title:null, url:"../pages/subscribe/subscribe.html?https%3A%2F%2Frss.golem.de%2Frss.php%3Ffeed%3DRSS1.0", windowId:null}]}))
TypeError: browser is null
BrowserElementParent.jsm:81:21
NS_ERROR_UNEXPECTED: 
```

This is printed every time I enter the subscription page.
On FF 71, Fedora 31

**Comment by rmader** [comment]
This has somehow got fixed - never mind :)
