### ISSUE TITLE
Don't detect RDF files as feeds

### ISSUE THREAD

**Issue by ath0mas** [nt1m/livemarks#218]
**Add-on version**
2.4.1

**Describe the bug**
Livemarks tries to open RDF file url but fails to load it: `Error: "feed is undefined" subscribe.js:84:13`

**To Reproduce**
1. Go to https://www.imagemagick.org/download/
2. Click on [digest.rdf](https://www.imagemagick.org/download/digest.rdf)

**Expected behavior**
Livemarks should not open RDF file url? or without error?

**Comment by nt1m** [comment]
Actually, RDF files really shouldn't be detected as feeds.

**Comment by evilpie** [comment]
I think the safest approach would be to actually parse the feed in the "load-preview" background handler, before calling `Feedpreview.show`. That is similar to what we do in the `chrome.webRequest.onHeadersReceived` listener.
