### ISSUE TITLE
Gmail issue?

### ISSUE THREAD

**Issue by GrosBourrin** [nt1m/livemarks#227]
URL issue : https://mail.google.com/mail/u/0/feed/atom
Add-on version: 2.6
i can't have my gmail feed ! it says it can recover the feed !
This issue occurs since a few monthes now

**Comment by nt1m** [comment]
Does disabling Tracking Protection solve the issue ?

**Comment by GrosBourrin** [comment]
nope !

**Comment by evilpie** [comment]
I think the only way forward is to get someone to fix this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1502987) in Firefox

**Comment by GrosBourrin** [comment]
> 
> 
> I think the only way forward is to get someone to fix this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1502987) in Firefox

i agree

**Comment by TheOncomingStorm** [comment]
So is there any update on this? when I go to gmail, Livemarks offers me the opportunity to add the feed but when I attempt to add it it gives an error of "failed to fetch feed" BUT when I click on the "view source" link it shows the feed as I would expect it. Is there something that's allowing Livemarks to be able to see the feed but not able to read it?

**Comment by GrosBourrin** [comment]
![2020-03-27_01h18_24](https://user-images.githubusercontent.com/40931468/77708639-e25b5480-6fc8-11ea-8963-28f1249fecf2.png)
here is what i have when i try to catch the gmail feed "impossible to catch the feed" or something like this, sorry i'm french

**Comment by nt1m** [comment]
@GrosBourrin Thanks! I'm French too so no worries :) 

So, there seems to be 2 issues:
1. the XHR to https://mail.google.com/mail/u/1/feed/atom gives you a 401 status, so it seems like Gmail doesn't want people to XHR the feed.
2. This console error: `Request to access cookie or storage on “https://mail.google.com/mail/u/1/feed/atom” was blocked because it came from a tracker and content blocking is enabled.`

I wonder if there are other APIs allowing us to workaround 1 (which may fix this issue), 2 can't be fixed without https://bugzilla.mozilla.org/show_bug.cgi?id=1502987 .

**Comment by TheOncomingStorm** [comment]
Ok, so thus far the feed was updated once and then it stopped which doesn't make a whole lot of sense, and the add-on I am using doesn't let me set the refresh period(that I can find) so I have no idea if it will update again but I'll let you know what happens in the next few hours.

**Comment by nt1m** [comment]
@TheOncomingStorm Thanks for the update, that seems strange.

Btw, you mentioned another RSS reader works, which one is it ? This way we could look at how it's doing things.

**Comment by evilpie** [comment]
I am going to try and compare the HTTP headers send when doing `fetch` in the webconsole on mail.google.com compared to a background XHR. I am curious how Google servers can tell the difference.

**Comment by TheOncomingStorm** [comment]
@nt1m it is Awesome RSS.  https://shgysk8zer0.github.io/

It doesn't seem to have updated my feed again so I'm kinda at a loss as to what happened. Maybe installing it allowed it a moment where it could grab it but whatever it is, I haven't yet worked it out. I do know I had not disabled Livemarks when I installed it so who knows.  I'll keep searching for a solution because this is the best way for me to keep up with all my email..

**Comment by nt1m** [comment]
Thanks! From what I can see, Awesome RSS just redirects to the raw feed. You can view the raw feed going to the feed url shown by livemarks (above the "View source" link).

**Comment by TheOncomingStorm** [comment]
Well, it will give you a few ways to subscribe if you check the preferences. I just told it to use RSS.

**Comment by evilpie** [comment]
> Well, it will give you a few ways to subscribe if you check the preferences. I just told it to use RSS.
Can you maybe take a screenshot showing us what you mean?

When I click the link it literally just opens https://mail.google.com/mail/u/0/feed/atom, which is just a raw XML document. Looking at the code https://github.com/shgysk8zer0/awesome-rss/blob/master/js/background.js, there doesn't seem anything in this extension that actually loads or parses RSS feeds.

**Comment by evilpie** [comment]
I am pretty sure we get that HTTP 401, because we are not sending Cookies, which we can't send because tracking protection is stripping them ...

**Comment by evilpie** [comment]
I actually figure out how to hack around this problem. By requesting the `cookies` permission we can lookup the required cookies ourself and add them to the request.
I don't think we should do this, adding the `cookies` permissions will ask the users for additional permissions during updates, and it's doubt people will understand why we need it.

https://github.com/evilpie/livemarks/commit/ff996813a6601e0585c5c24d176badc3940ac30e

**Comment by TheOncomingStorm** [comment]
My feed just updated again for no reason that I can quite figure out. I did have to restart Firefox but that's never triggered a feed update before that I know of, and restarting it again got me nothing. Something is causing Livemarks to work, if even just for a moment.

**Comment by evilpie** [comment]
Mozilla just fixed this with [bug 1629436](https://bugzilla.mozilla.org/show_bug.cgi?id=1629436). The current Nightly (77) now allows access to gmail.
