### ISSUE TITLE
Feed stopped updating and is only showing old entries despite new posts

### ISSUE THREAD

**Issue by PaulLFC** [nt1m/livemarks#229]
For the most part, Livemarks is working very well. However, I have one feed which is a custom feed from the 'HotUKDeals' deals website. The URL for this feed is http://www.hotukdeals.com/rssx/-KNvpt67aqqaPMoVhGBts1zBHKlzRF_mFYnl9aLAOs0

This feed was working fine in Livemarks up until December 23rd - on that date it stopped updating with new entries. If I paste that feed URL into Chrome, I can see that there have been new entries up to and including today. However, pasting the feed into Firefox shows the last post as December 23rd.

I'm not sure if this issue is related to Livemarks or something to do with Firefox. I've tried clearing Firefox's cache but the feed still shows as not having updated since December, despite Chrome and the site itself showing differently.

**Comment by evilpie** [comment]
I see deals from January 25 when opening the URL in Firefox. I suggest deleting all local data for that site, instead of just the cache.
Goto about:preferences and search for "Manage Data".

**Comment by PaulLFC** [comment]
Thank you, that fixed it! Deals from Jan 25th are showing now, and once I re-added the livemark it's updating correctly after clearing the local data. Thanks for the help!
