### ISSUE TITLE
Livemarks not updating

### ISSUE THREAD

**Issue by yenic** [nt1m/livemarks#23]
I have it set to a 5 minute interval, my feeds haven't updated in days. I tried changing the rate to 1 minute, no difference. 
![38841978_2033049786734855_8787116252796551168_n](https://user-images.githubusercontent.com/3839302/43939690-59137246-9c31-11e8-9024-46dda89b5413.png)

**Comment by ali1234** [comment]
Same here.

I checked the server logs and it is definitely fetching the feeds at the correct interval. It just never updates the bookmarks.

**Comment by rcmcronny** [comment]
My feeds are updated, all but 1 ...(golem.de feed is not updating since the beginning, but new articles are in the feed of course)

**Comment by ali1234** [comment]
I should mention this only happen after "a while" - seems like about a day.

**Comment by ali1234** [comment]
It most definitely isn't a problem on the server end since I have root access to the server and can monitor the logs.

The right click menu doesn't work. I wasn't sure whether it is even supposed to.

**Comment by marczellm** [comment]
I have the same problem. Also I don't see the context menu option at all.

I use Firefox Sync, is it possible that that messed something up?

**Comment by ali1234** [comment]
I made a bug report for the context menu at #24

**Comment by nt1m** [comment]
@ali1234 @yenic Can you send me the feed url ? There might be bugs with specific types of feeds that I haven't found yet.

**Comment by ali1234** [comment]
My feed is generated by this: https://github.com/ali1234/ytsubs

**Comment by yenic** [comment]
I found some of mine are now working, at a point, I didn't think any were getting updated. I'm almost completely sure that these all were not working before a recent system restart at least.
But checking right now, this is a complete list-

Not working
http://news.ycombinator.com/rss
http://www.anandtech.com/rss/
http://www.sciencemag.org/rss/news_current.xml
http://www.shacknews.com/rss?recent_articles=1
http://stallman.org/rss/rss.xml
https://mt-pleasant-ia.villagesoup.com/rss/story/news this one is relatively updated compared to the rest, and appears that it's almost up to date but it stopped. Both native Livemarks and addon Livemarks have published elements from 8/10, but the addon is missing the two most recent updates in the addon.

Working
http://www.computerworld.com/news/index.rss
https://rss.sciencedaily.com/all.xml
http://loudwire.com/feed/
https://slickdeals.net/newsearch.php?mode=frontpage&searcharea=deals&searchin=first&rss=1
http://www.shacknews.com/rss?recent_articles=1
http://www.chicagotribune.com/news/rss2.0.xml
http://feeds.bbci.co.uk/news/rss.xml?edition=us

**Comment by yenic** [comment]
I've updated my comment, testing my feeds now that its been a few days. Results are largely the same as the first time I compared native vs addon feeds. I did find 4 specifically with weird behavior that I think are worth using for your tests as the fix you identified is implemented.
They may lead to discovering more issues.

**Comment by yenic** [comment]
I haven't tested it as I thought it was going to be pushed to AMO before FF63-64, since this is a breaking issue that will drive off many new adopters as they remove the old functionality. I'm still using the built-in LiveBookmarks.

**Comment by nt1m** [comment]
@ali1234 @marczellm @yenic Sorry, I've been extremely busy this last month.
I've published a new release on AMO, please let me know if there are other issues.

**Comment by yenic** [comment]
I just updated and tested all my feeds, it appears to be resolved for all of them. My feed set is diverse enough, I'll continue to keep an eye on both LiveMarks and LiveBookmarks.

The only thing that stood out immediately was an existing issue with no unread vs read icon change for most feeds, which I believe is what https://github.com/nt1m/livemarks/issues/17 is for. I added a comment over there.

**Comment by LoneBoco** [comment]
@nt1m It turns out that some feeds don't list a lastBuildDate nor a pubDate.  In this situation, the feed doesn't update at all.  In the RSS 2.0 spec, only the title, link, and description are required.

An example of a feed that lacks this information:
http://rss.slashdot.org/Slashdot/slashdotMain

I'm not sure what a good solution to this problem would be.  Maybe remember the latest item by URL and timestamp it with the date and time it was retrieved?

**Comment by marczellm** [comment]
It would be worth looking at how Firefox solved this problem.

**Comment by nt1m** [comment]
A quick fix would be augmenting [this condition](https://github.com/nt1m/livemarks/blob/master/background/background.js#L62) to be: `if (!feedData.updated && feedData.updated == feed.updated && !forceUpdate) {`.

That would make the feeds without any updated date to be refetched regularly, and the bookmarks folder to be repopulated regularly too.
