### ISSUE TITLE
Livemarks does not parse isPermaLink=false

### ISSUE THREAD

**Issue by denis-roy** [nt1m/livemarks#233]
**Add-on version**
v2.7

**Describe the bug**
Livemarks does not parse "isPermaLink=false" which yields an invalid URL that leads to a 404

**To Reproduce**
1. Register a feed that uses the tag, for exemple the [freefilesync.org feed](https://freefilesync.org/news-feed.php)
2. Open Livemarks and hover on an item's link

![gnelidmcmlbaedbf](https://user-images.githubusercontent.com/3801326/77535628-4a972280-6e71-11ea-987b-00cc1ffba8d0.png)

Notes: 

- The feed is deemed valid RSS by [feedvalidator.org](http://www.feedvalidator.org/check.cgi?url=https%3A//freefilesync.org/news-feed.php)

**Comment by nt1m** [comment]
Thanks for reporting! Seems like isPermaLink should be taken in account according to: https://validator.w3.org/feed/docs/rss2.html#ltguidgtSubelementOfLtitemgt 

I'll make items like this redirect to `https://<website-homepage>/?itemguid=<guid>` (the `?itemguid=<guid>` bit is so the read indicator would still work).
