### ISSUE TITLE
Add Preview to Livebookmarks

### ISSUE THREAD

**Issue by LordSky00** [nt1m/livemarks#239]
I use the preview window for one of my podcast to add the episode descriptions to the comment section of my podcast mp3s. Could you add a link to the RSS preview right after the link to RSS link home page (in the livebookmarks; first item) Or at least a way to get to back to the preview layout.

Also could you also prompt where to Add livebookmarks for each RSS feed rather than one default location? This way, I can change the title and where it will be placed all at once. 

Thank you so much for this extension. I was stuck on Firefox 26.0.3 until I found this extension.

**Comment by nt1m** [comment]
@LordSky00 For your specific feature request, you should be able to set the "Site URL" setting of each feed to the feed URL, and clicking on the "Open" link should work as expected.

If that doesn't work for you, please feel free to let me know :)
