### ISSUE TITLE
Update menu doesn't work

### ISSUE THREAD

**Issue by ali1234** [nt1m/livemarks#24]
The update menu which is supposed to appear on livemark directories doesn't show up.

If I change the code from:

    LivemarkUpdater.init().then(() => ContextMenu.init());

to:

    LivemarkUpdater.init();
    ContextMenu.init();

then it shows up on every bookmark folder (even ones which do not contain livemarks), and when I click it nothing happens.

**Comment by ali1234** [comment]
61.0.1 (64-bit) - Ubuntu standard package

**Comment by yenic** [comment]
Same thing here, along with not updating as per #23. Firefox 61.0.2 64-bit Windows 10 
![image](https://user-images.githubusercontent.com/3839302/43996239-ffabc092-9d83-11e8-9b7f-2bd71982ce5e.png)
Other extensions installed, maybe this is relevant in duplicating.
![image](https://user-images.githubusercontent.com/3839302/43996263-7f591a6a-9d84-11e8-99ba-c06a60b94b92.png)

**Comment by nt1m** [comment]
@ali1234 You seem to be hitting this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1473720
It has been fixed from Firefox 62 onwards.

@yenic WebExtension context menus unfortunately don't work in the bookmarks sidebar. [This bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1419195) aims to fix this.

**Comment by yenic** [comment]
It wasn't working for me on the toolbar before either. I moved all my Livemarks extension feeds into Other Bookmarks and went back to using FF's native support until #23 & #24 are sorted out. I just tried again with it on the toolbar.
![image](https://user-images.githubusercontent.com/3839302/43996392-7ff0b1ce-9d87-11e8-9315-200d5256656c.png)

**Comment by nt1m** [comment]
@yenic The toolbar seems to be hit by this Firefox bug which is fixed in 62: https://bugzilla.mozilla.org/show_bug.cgi?id=1473720

It can be worked around, but it's not a pretty solution unfortunately.

**Comment by yenic** [comment]
I can wait for FF62, not a problem. Thanks.

**Comment by nt1m** [comment]
@yenic @ali1234 Does the menu work in Firefox 62 now ?

**Comment by ali1234** [comment]
Yes, it seems to. If I am quick I can see the items reappearing in the menu.

**Comment by nt1m** [comment]
OK, thanks. I'll wait for @yenic confirmation as well.

**Comment by ali1234** [comment]
Tried it with lorem-rss and it works.

**Comment by yenic** [comment]
It's working for me.
![image](https://user-images.githubusercontent.com/3839302/46920029-b2271e00-cfad-11e8-842d-2fb7c69766fb.png)

**Comment by nt1m** [comment]
Thanks!
