### ISSUE TITLE
Have an option "Open all entries not read (yet)"

### ISSUE THREAD

**Issue by LaurentGrenet** [nt1m/livemarks#242]
Beside existing option "Open all in tabs" ("Tout ouvrir dans des onglets" in french, I do not know exact wording in english....), or maybe replacing this option, it would be great to have an option "Open all not read in tab" ... that open all not read entries, each in a separate tab.

In case all entries are already "read", we could imagine
- that the option is not there
- or it is greyed and not usable
- or it only dispaly an error popup "All entries are already read"

This at least in case prefixes are defined / set to mark entries read / not read.

This woud make Livemarks, that is already a great extension, an even greater module !

**Comment by nt1m** [comment]
Great suggestion, thanks! I'll look into it when my time frees up a little bit more next month, should be fairly straightforward :)

**Comment by hyde-stevenson** [comment]
That's nice ! I was wondering the same thing

**Comment by LaurentGrenet** [comment]
I post again, just to remind you the request, in case you forgot it....

**Comment by nt1m** [comment]
This has been fixed and will be in the next version.
