### ISSUE TITLE
Add a way to see links not read yet

### ISSUE THREAD

**Issue by hyde-stevenson** [nt1m/livemarks#248]
Hello,

I follow a lot of blogs but I have to go through each directory to see if there are any new article. 

It would be nice to have a way to have all links in the same directory maybe or small icons on directories where updates are available. 

Let me know if I'm not clear enough.

Thanks

**Comment by nt1m** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/1795135/83024352-8f386900-a02e-11ea-9550-c9286f1c4420.png">

Hi, thanks for the suggestion. Does turning on the "Show on folders when all their items are read/unread" setting provide the functionality you need?

**Comment by hyde-stevenson** [comment]
Hello, 

Yeah it should be good I guess :)

**Comment by nt1m** [comment]
Cool, thanks! :) I'll close the issue for now, let me know if you need anything else!

**Comment by hyde-stevenson** [comment]
Perfect thanks :) I'm waiting for the other one I'm currently watching :)
