### ISSUE TITLE
Doesn't work with GitHub

### ISSUE THREAD

**Issue by irvnriir** [nt1m/livemarks#250]
**Feed URL**
https://github.com/ , the subscribe is at bottom .

**Add-on version**
last

**Describe the bug**
Nothing happens when click Add .. .

**Comment by evilpie** [comment]
What do you mean at the bottom? When I go to github.com while logged in and click on the RSS icon inside the address bar I can successfully add my private RSS feed.

**Comment by irvnriir** [comment]
https://www.youtube.com/watch?v=TB36DIVHGGg&feature=youtu.be

**Comment by evilpie** [comment]
I thought this would be another instance of https://github.com/nt1m/livemarks/issues/38, which should have been fixed in Firefox 77. Are you using private browsing mode?

**Comment by evilpie** [comment]
Do you see any errors in the web console or browser console?

**Comment by irvnriir** [comment]
Private mode was just to disable Add-ons, no errors .

**Comment by evilpie** [comment]
Not sure how to help you. I suggest creating a completely new profile (e.g. via about:profiles) and *only* installing Livemarks in it. If it works there you know something is broken with your normal profile.

**Comment by irvnriir** [comment]
It coincidentally needed to refresh Firefox, on a completely clean install its completely same.

**Comment by evilpie** [comment]
![Screen Shot 2020-06-20 at 13 24 27](https://user-images.githubusercontent.com/296445/85200625-650a5c00-b2f9-11ea-97e2-ff0c518d2332.png)

I can't reproduce this problem.

**Comment by irvnriir** [comment]
looks like it doesn't work when there is no items yet (alike on a new account) .

**Comment by evilpie** [comment]
Thanks, that actually makes sense. We don't allow adding empty feeds, because that usually means something went wrong during parsing.

**Comment by irvnriir** [comment]
@evilpie that probably should be reconsidered .
