### ISSUE TITLE
Problem with a feed (5-4 Pod)

### ISSUE THREAD

**Issue by thegreatprophetzarquon** [nt1m/livemarks#252]
**Feed URL**
https://feeds.megaphone.fm/WWO5591736705

**Add-on version**
2.8

**Describe the bug**
This feed displays in the browser window (feed preview), but when added to the bookmark bar the folder remains empty, even on refresh. 

Firefox 77.0.1

**Comment by evilpie** [comment]
Thanks. The problem is that the feed doesn't contain an URL per feed item and bookmarks in Firefox require an URL.
