### ISSUE TITLE
Unable to delete invalid feeds

### ISSUE THREAD

**Issue by EverEve** [nt1m/livemarks#269]
Hello, only today I've noticed I have a group of invalid RSS.
I cannot delete them, the only way to get rid of them is to create a bookmarks folder and put them into it. Then delete the folder.

Tried both on Windows and Linux.

![invalid](https://user-images.githubusercontent.com/6781183/90910867-5cf19a00-e3d8-11ea-8ebc-fce7d3f932d2.png)

Thanks for your attention

**Comment by evilpie** [comment]
Thanks! This was actually fixed by #265.
