### ISSUE TITLE
Show livemarks button directly on feed URL pages

### ISSUE THREAD

**Issue by wesinator** [nt1m/livemarks#27]
It would be useful if the Livemarks button was displayed directly on feed XML pages, so users can manually add a feed if the feed_finder did not detect the feed, or the user accesses the feed URL directly.

![image](https://user-images.githubusercontent.com/5124946/45985188-1308a980-c033-11e8-9655-3a4bf315565c.png)

https://feeds.feedburner.com/GoogleBlog
**Expected:** Page detected as feed, Livemarks button in address bar.
**Actual:** No livemarks button

Thanks

**Comment by nt1m** [comment]
When Firefox actually drops support for the pretty "Subscribe to this Feed" page, this will start working.

**Comment by evilpie** [comment]
#45 got this working on some pages. This particular page https://feeds.feedburner.com/GoogleBlog doesn't work, because it uses `Content-Type: text/xml` and XSLT. We do show the feed icon in the URL bar.

**Comment by evilpie** [comment]
I actually wonder if we should special case feeds.feedburner.com, it seems to be one of the most popular feed websites. Google including blogspot uses it.
