### ISSUE TITLE
Preview feed issue with neowin websire

### ISSUE THREAD

**Issue by GrosBourrin** [nt1m/livemarks#270]
**Feed URL**
Please specify the feed URL: https://www.neowin.net/news/rss/software/

**Add-on version**
Add-on version: 2.8

When i visit the preview of the feed for this website, pictures overcover the  boxes as on the pic .
Is it relative to the website or is this a bug from the webext ?

![2020-08-22_13h38_11](https://user-images.githubusercontent.com/40931468/90955387-6c76ee80-e47d-11ea-9a98-5612ae901a56.png)

![2020-08-22_13h28_01](https://user-images.githubusercontent.com/40931468/90955389-6ed94880-e47d-11ea-8445-601f9a662509.png)

is it relative to the website or this is a bug from the webext ?

**Comment by evilpie** [comment]
Those pictures have the following style `float:left;margin-right:10px;`, which is part of the RSS feed. So that margin seems to be intentional for some reason. So far we haven't bothered with stripping CSS.

**Comment by GrosBourrin** [comment]
ok :) thanks for answer
