### ISSUE TITLE
Livemarks fails to load this feed: https://www.cnews.cz/hardware/feed/

### ISSUE THREAD

**Issue by klopcz** [nt1m/livemarks#277]
I tried to use this feed https://www.cnews.cz/hardware/feed/ in Livemarks, but Livemarks fails to load it. It is strange because in the past it worked.

Thank you in advance for your attention.

**Comment by evilpie** [comment]
The XML of this feed is invalid.

> XML Parsing Error: prefix not bound to a namespace
> Location: https://www.cnews.cz/hardware/feed/
> Line Number 47, Column 3:

It's using `<media:thumbnail ..>`, but the rss tag is missing `xmlns:media` like `<rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/">`. (https://www.rssboard.org/media-rss)

**Comment by klopcz** [comment]
Thank you for your feedback. I'll try to report it at mentioned web.
