### ISSUE TITLE
Hide links already read

### ISSUE THREAD

**Issue by hyde-stevenson** [nt1m/livemarks#279]
Hello,

I follow a lot of blogs and I would find really useful to be able to hide the links already read. That way I can "Open all links in tabs" and avoid to do it manually. 

It's maybe possible to add a button to open all links "not read yet" only ... 

Let me know :) 

And thanks for this addon :+1:

**Comment by evilpie** [comment]
#242 added an option to open all unread links via the context menu.

**Comment by hyde-stevenson** [comment]
ok thanks :) 

btw when can we see a new release roll out ?  What's the scheduling ?

**Comment by evilpie** [comment]
Version 3.0 is now live

**Comment by hyde-stevenson** [comment]
YOUHOOOOOU ! Great ! 
thanks !
