### ISSUE TITLE
Should livemarks use the sidebar api ?

### ISSUE THREAD

**Issue by baloone** [nt1m/livemarks#289]
If the [sidebarAction api](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction) is used, livemarks will not be in the "Recently Bookmarked" folder nor in the suggestions of the research bar.
It may also use custom icons instead of a prefix for the pages read etc.

**Comment by evilpie** [comment]
No. There are various other RSS extensions for Firefox that could this. We specifically want to replace live bookmarks, which were/are special kind of bookmarks.
