### ISSUE TITLE
A11y fix removeing a feed.

### ISSUE THREAD

**Issue by tapper82** [nt1m/livemarks#322]
Hi I am using NVDA a Screen reader for the blind. 
https://www.nvaccess.org/
on Windows 10 Firefox 86.01  Nightly. Livemarks 3.1 
I cant find a way to remove a rss feed from the dashboard.
After opening the options and looking at the list of feeds it just says "button" I know it's a small fix but would make life better for me thanks.

**Comment by nt1m** [comment]
Sorry about that, I noticed there is indeed a missing label on the button showing the edit dialog: https://github.com/nt1m/livemarks/blob/master/pages/settings/settings.js#L181

I'll take care of it as soon as I can. Thanks for reporting.

Other than that, one way you can delete the feed is to delete the bookmark folder itself representing the live bookmark.

**Comment by tapper82** [comment]
Thank you.

**Comment by evilpie** [comment]
I hope a `title` attribute will be read out to you. I don't currently know how to test this.

**Comment by tapper82** [comment]
Hi as soon as it updates in my firefox I will test and let you know. Thanks.
