### ISSUE TITLE
Livemarks appear in parent folder (bookmark menu)

### ISSUE THREAD

**Issue by sadrklghxduklyipasdthguzeriparp** [nt1m/livemarks#336]
**Add-on version**
3.2, Firefox 85.0

**Describe the bug**
Livemarks appear where they are not supposed to be. 

**To Reproduce**
no idea

**Expected behavior**
Livemarks should only appear in the assigned folder.

**Comment by evilpie** [comment]
Are you using the default bookmark extension?

**Comment by evilpie** [comment]
I meant "Default Bookmark Folder", which would make this a duplicate of #332. @sadrklghxduklyipasdthguzeriparp

**Comment by sadrklghxduklyipasdthguzeriparp** [comment]
I am indeed! Thanks for pointing it out! @evilpie
