### ISSUE TITLE
Java desabled after reading a feed

### ISSUE THREAD

**Issue by HenriQuatre** [nt1m/livemarks#339]
Hello,
I'm really a newbie here. My apologies if the subject was mentioned, but I couldn't find anything through the search process.

**Add-on version**
Add-on version: 3.2 (15/02/2021) and some previous

**Describe the bug**
After reading a feed, like [https://www.liberation.fr/arc/outboundfeeds/rss/?outputType=xml] or [https://korben.info/feed] or [https://guzzitek.org/rss.xml], Java is disabled on Firefox 85.0.2 and previous versions since some monthes

**To Reproduce**

Just going to the feed and some seconds after, the Java is desabled in Firefox. I have to relaunch FF and that's OK again.
For exemple, DuckDuck Go screen become (see screen copy)

![Capture d’écran 2021-02-18 à 12 57 47](https://user-images.githubusercontent.com/79258541/108354003-1f37c780-71e9-11eb-93f1-65f42c34bc8a.jpg)

Thank you and sorry for my poor english

H4

**Comment by evilpie** [comment]
Thanks for the report. This should be fixed by https://github.com/nt1m/livemarks/commit/1bd0f6964e13432ef9972e8c233eed30ca3b5975. We are going to release a new version with this sometime soon.
