### ISSUE TITLE
Valid Slashdot feed fails

### ISSUE THREAD

**Issue by scopulorum** [nt1m/livemarks#347]
**Feed URL**
  http://rss.slashdot.org/Slashdot/slashdotMain

Feed validation:
  https://validator.w3.org/feed/check.cgi?url=http%3A//rss.slashdot.org/Slashdot/slashdotMain
  Yes it's a stinky mess, but it is valid.

**Add-on version**
Add-on version: 3.3 , updated February 24, 2021
Browser version: Firefox 87.0 (64-bit)

**Describe the bug**
"Failed to fetch feed "
moz-extension://b95fe5ee-01c7-ca47-a266-db3d203d7cd1/pages/subscribe/subscribe.html?http%3A%2F%2Frss.slashdot.org%2Fslashdot%2FslashdotMain

**To Reproduce**
1. go to https://slashdot.org/
2. click site RSS icon in upper right ( leads to http://rss.slashdot.org/Slashdot/slashdotMain )
3. click livemarks rss icon in location bar

**Expected behavior**
add livemarks rss feed

**Comment by evilpie** [comment]
Do you have HTTPS-only mode enabled in Firefox? Switching that off fixed it for me.

**Comment by scopulorum** [comment]
Thanks for the response.

I do. That did fix it. Since slashdot seems to be the most notable site that has the issues ( I’m not aware of any other RSS feed with the issue ) , it would be nice to know what they are doing that causes the problem and pass it on ( and be disappointed that they don’t change anything ).

Cheers,

Juniper

**Comment by evilpie** [comment]
They need to host their RSS feed with HTTPS support, i.e. https://rss.slashdot.org/Slashdot/slashdotMain should work.
