### ISSUE TITLE
format of screen shot

### ISSUE THREAD

**Issue by wd0d** [nt1m/livemarks#348]
I cannot find a setting in Livemarks that will allow me to duplicate the screenshot shown on the Livemarks website. I want the single topic line format, not the more elaborate 
"Ukraine conflict: Moscow could 'defend' Russia-backed rebels
April 8, 2021, 4:32 PM
A senior Kremlin official issues a warning as tensions rise in eastern Ukraine."
wd0d

**Comment by evilpie** [comment]
I am not sure what screenshot or format you are talking about. I assume you mean the preview page. The amount of text depends on what the RSS feed provides. For example https://feeds.bbci.co.uk/news/rss.xml is fairly short.

**Comment by wd0d** [comment]
Thanks for the quick response. I may have misread what was shown on the
add-on site. What I'm looking for is something like the old live bookmarks
"bullet point" topic lines. Single spaced, each line a different story.
Sort of a "headline" list. May not be possible.
Thanks.
wd0d

**Comment by evilpie** [comment]
Please provide a screenshot. I am still not sure if you are talking about the preview page or the actual "Livemarks" in the bookmarks menu of Firefox.

Please note that it's very unlikely that we will make significant changes to either.

**Comment by wd0d** [comment]
Tom,
I finally figured out what I need to do. I didn't realize that Livemarks
creates a bookmark folder with constantly updating topics. By placing the
folder, for say the BBC, on my Bookmarks toolbar, I can now click on it and
get exactly what I want.
[image: Livemarks folder.jpg]
Maybe I'm using Livemarks the wrong way, but I am getting the result that I
want.
Thanks.
Bob
