### ISSUE TITLE
+ add a way to preview images in feed (hover modal?) // imageboard rss

### ISSUE THREAD

**Issue by atlcell** [nt1m/livemarks#362]
**Describe the solution you'd like**
Can we please figure out a way to add imageboard support? 

to get to the point, this is the solution illustrated

![Screen-Shot-2021-07-17-at-9 29 14-PM](https://user-images.githubusercontent.com/1452704/126053094-688bac60-ec43-4ac6-ab05-d94cfd9aa978.jpg)

Example feeds 
https://boards.4channel.org/g/catalog
https://boards.4channel.org/g/index.rss

Imageboards are..imageboards. The image that correlates with a post is very important. Across the board, if an RSS post has an image in it, it would be nice to preview said image without having to open the page. 

I only have three RSS feeds I follow. HN, /g/, and my cities subreddit so I'm not burning myself out with information overload :)

Could you guys give me the direction to do this? Is it possible to create an image modal in the context menu with the data from the rss feed? Can I get some pointers so either I could implement it myself, or pay you guys to write it with a donation? :)

Thank You

**Comment by atlcell** [comment]
@nt1m @evilpie I tagging you guys just because you are the major contributors and also have the last human commit. 

Just doing preliminary research into available avenues
https://stackoverflow.com/questions/14423923/chrome-extension-modal-dialog-or-other-solution-to-notify-users
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create

line `316` in `background.js` - https://github.com/nt1m/livemarks/blob/master/background/background.js, with that blob, either render the image if possible using `browser.menus` api, or create an html page and inject the iframe into the current page. 

Do those approaches come to your mind?

**Comment by atlcell** [comment]
I actually opened an issue 2 years ago, lol

https://github.com/nt1m/livemarks/issues/216

**Comment by evilpie** [comment]
Not possible
