### ISSUE TITLE
Implement diffing for populating bookmark folders

### ISSUE THREAD

**Issue by nt1m** [nt1m/livemarks#37]
https://www.npmjs.com/package/fast-array-diff

Right now, for updates, we just clear the bookmark list and then repopulate it. This is incredibly unefficient, especially for feeds with no last updated date.

**Comment by nt1m** [comment]
I don't have time to work on this immediately, but I'll happily accept a PR, even one that uses a third party lib

**Comment by thomcc** [comment]
This also causes a lot of problems for Firefox sync, which stores data on bookmark deletions (so that it can distinguish between "never seen this" and "saw it but deleted it").

See https://bugzilla.mozilla.org/show_bug.cgi?id=1499881

**Comment by nt1m** [comment]
I think #41 is enough, and there's no point of doing #41
