### ISSUE TITLE
Neowin software update feed broken ?

### ISSUE THREAD

**Issue by GrosBourrin** [nt1m/livemarks#373]
**Feed URL**
Please specify the feed URL: https://www.neowin.net/news/tag/software/ or https://www.neowin.net/news/cat/software/

**Add-on version**
Add-on version: 3.3 Firefox 93.0 on Windows 10

**Describe the bug**
Relative to Neowin website rss feeds for software update: livemarks displays ads of  the feed and not the list of updates of the software 

here is the feed : 
![2021-10-05_17h22_27](https://user-images.githubusercontent.com/40931468/136054453-28dd9489-dd5a-4ee5-9fd4-9b41bdf715bb.png)

here is the website software tab 
![2021-10-05_17h24_47](https://user-images.githubusercontent.com/40931468/136054554-dd420b18-5587-47da-bf35-e39a0d462abb.png)

**Comment by evilpie** [comment]
If you look at the source of that feed it becomes obvious that it's only ads: `view-source:https://www.neowin.net/news/rss/software/`

**Comment by GrosBourrin** [comment]
there was a list of updates software as on the site, maybe they broke it
