### ISSUE TITLE
Firefox's tracking protection can interfere with feed requests

### ISSUE THREAD

**Issue by mafro1** [nt1m/livemarks#38]
Icon for livemarks shows up for reddit.com homepage but live feed preview displays nothing and it doesn't pull anything into the bookmark. (site url or feed). I originally imported this using the firefox generated opml file then deleted and manually tried to add https://www.reddit.com/.rss  

any suggestions?

**Comment by eikaramba** [comment]
the issue is because of "tracking protection" feature in FF. i disabled it and now it works. need more debugging to see how to get around this without disabling the whole feature

**Comment by nt1m** [comment]
@evilpie Maybe we could add a notification when a feed failed to fetch ? With an indication that tracking protection might be behind the problem

**Comment by nt1m** [comment]
Filed a bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1514054

**Comment by nt1m** [comment]
It seems like we can start prompting optional permissions for the hosts we want to bypass tracking protection from.

**Comment by nt1m** [comment]
I'm working on a way to work around this.

**Comment by belegdol** [comment]
How do I whitelist Reddit so that the extension works? I clicked the shield icon while on the subreddit in question and selected to disable on this page, but the RSS feed still does not load.

**Comment by nt1m** [comment]
Black Menu for Google opens up an extension page that allows you to unblock content blocking. Maybe that can be used here: <img width="1680" alt="image" src="https://user-images.githubusercontent.com/1795135/59563958-01dc4e80-9041-11e9-8cf4-63265def8f96.png">

**Comment by nt1m** [comment]
<img width="598" alt="image" src="https://user-images.githubusercontent.com/1795135/59563981-3c45eb80-9041-11e9-9daf-64691c532b58.png">

**Comment by evilpie** [comment]
This should now finally be fixed in Firefox 77 by https://bugzilla.mozilla.org/show_bug.cgi?id=1629436.

**Comment by nt1m** [comment]
@evilpie Thanks for following and updating the issue!
