### ISSUE TITLE
Can't add private internal feed URLs

### ISSUE THREAD

**Issue by SirJimmothy** [nt1m/livemarks#390]
**Add-on version**
Add-on version: 3.4

**Describe the bug**
In attempting to add an internal feed, LiveMarks simply outputs "failed to fetch feed". I've run the feed itself through an RSS validator which works fine, so I'm presuming the issue is related to the HTTP authentication required, or the fact that it's hosted on an internal-only domain, and for some reason, this may be being processed outside of my browser context.

Example URL: https://devportal.dev.ourdomain.net/staff/servers.rss

I built the RSS feed into our internal company portal for the sole purpose of ease of access for staff, but if the feed processor runs outside of our browser context, this functionality is unreachable.

**Comment by nt1m** [comment]
The request is made in the browser, however, maybe it needs some authentication http header, or a certain cookie attached.

**Comment by SirJimmothy** [comment]
It is certainly set up to be behind HTTP authentication, but this is not being prompted for.

**Comment by evilpie** [comment]
The request is being done in the background page so there is no way to show an authentication prompt.

**Comment by SirJimmothy** [comment]
Ah well, not to worry. Shame this can't be implemented; it would be so useful.
