### ISSUE TITLE
Unable to read a feed

### ISSUE THREAD

**Issue by Armand68** [nt1m/livemarks#398]
**Feed URL**
[Please specify the feed URL: ](https://laviedesidees.fr/spip.php?page=backend)

**Add-on version**
Add-on version:3.4

**Describe the bug**
Livemarks is unable to read this feed, which was working properly a few days ago. Another addon of Firefox, Feedbro, reads the feed without any problem

**To Reproduce**
1. Go to '.[https://laviedesidees.fr]
2. Click on 'the icon of the feed and add the feed'
3. Scroll down to 'the menu where the feed are saved'

**Expected behavior**
Thanks for you work, your addon is really great (except when it don't work !)

**Comment by evilpie** [comment]
Firefox can not parse that XML.

> XML Parsing Error: XML or text declaration not at start of entity
> Location: https://laviedesidees.fr/spip.php?page=backend
> Line Number 2, Column 1:
