### ISSUE TITLE
NYTimes 'The Daily' not resolving correctly 

### ISSUE THREAD

**Issue by SDRoffey** [nt1m/livemarks#427]
**Feed URL**
Please specify the feed URL: https://feeds.simplecast.com/54nAGcIl

**Add-on version**
Add-on version: 3.5

**Describe the bug**
Fails to resolve RSS feed. Either shows the "This XML file does not appear to have any style information associated with it. The document tree is shown below." message or just a screen of text.

**To Reproduce**
Steps to reproduce the behaviour:
Just open the above URL.

**Expected behaviour**
It should list the episodes available.

**Comment by evilpie** [comment]
Works for me.

**Comment by SDRoffey** [comment]
Managed to fix this issue by uninstalling and reinstalling Firefox. Now working correctly.
