### ISSUE TITLE
Bookmark titles getting truncated

### ISSUE THREAD

**Issue by ali1234** [nt1m/livemarks#451]
Add-on version: 3.5
Firefox version: 113.0.2 (From Snap)

**Describe the bug**
The titles of some bookmarks are being truncated, even though there is plenty of space:

![image](https://github.com/nt1m/livemarks/assets/651970/d7d7f4f8-278a-4261-9240-5fb94963be3c)

**To Reproduce**
Not sure. It seems to happen randomly when the bookmark is reloaded. I have seen those same titles get rendered in full one of previous times this feed refreshed. It seems like it is more likely to happen to the items at the top than at the bottom. I checked the feed and the titles are not truncated there. Also, hovering the mouse over the items shows the full title. So this seems to be some change inside Firefox. 

**Expected behavior**
All items should be truncated to the same length. Note this is a regression.

**Extra context**
This may be related to my custom userchrome.css. I'll investigate that possibility next.

**Comment by ali1234** [comment]
The livemark reloaded and the problem disappeared even with my customizations on, so I'm not sure what is going on here.

Looking at the screenshot, it looks like the truncated bookmarks have the same length as the first fully shown one following them. Very weird.

Also I never noticed this happening with normal bookmark folders, although I don't use those very often.

**Comment by nt1m** [comment]
Are the titles truncated in the RSS feed itself?

**Comment by ali1234** [comment]
I can't be 100% sure because the feed updates every half an hour so by the time I notice the problem it has already changed. However I think it is unlikely because if the title is truncated in the RSS, then how can Firefox show me the full title when I mouse over? It only gets put into the `title` attribute and nowhere else in the RSS.

**Comment by ali1234** [comment]
Given the pattern in the lengths and the way it disappeared entirely when I reloaded, I would guess that this is somehow related to the order that the folder is populated when the feed changes. Possibly including changes to the title of existing videos, which I noticed happens a lot. Also due to the way I aggregate the data it is possible for new videos to show up in the middle of the list if they were private for a few hours after upload which is also not unusual.

**Comment by ali1234** [comment]
I can confirm it is not caused by my userchrome, nor it is a problem with the RSS feed itself. However, the problem can disappear even when the RSS does not change. I am not yet sure why.

**Comment by ali1234** [comment]
An update: if I have two browser windows open, it is possible that the truncation differs between them. If I open a new window, the titles are never truncated.

This looks more and more like a Firefox bug to me.

**Comment by nt1m** [comment]
@Emilio could this be a XUL layout bug?

**Comment by emilio** [comment]
Unlikely because that is gone :)

How are these rendered?

**Comment by ali1234** [comment]
Finally caught it happening with userchrome disabled:

![image](https://github.com/nt1m/livemarks/assets/651970/7d82acd5-ac6e-4578-8a08-fdee0f69d972)

Simultaneously, in another window, the same menu looks like this:

![image](https://github.com/nt1m/livemarks/assets/651970/9a69f472-a84e-456b-b991-737d41453a40)

I also noticed that when this happens, the truncated titles are usually in a browser window that I have not looked at for a while and is minimized, so it could be something like available space not being calculated correctly if there's no windowing context because the window is hidden.

Anyway I think I'll report this on bugzilla tomorrow.

**Comment by ali1234** [comment]
I forgot. But now I did it: https://bugzilla.mozilla.org/show_bug.cgi?id=1848526

**Comment by nt1m** [comment]
Closing as emilio fixed this in Firefox 121.
