### ISSUE TITLE
bookmarks limited to 25 in imported folder

### ISSUE THREAD

**Issue by Hoppaz** [nt1m/livemarks#457]
Add-on version: 3.5

I've created a atomfeed, which is shown fine on the first access to the page.
After adding it to the bookmarks only 25 entries are shown.

To reproduce:
1. install plugin
2. goto https://peamx.de/atom.xml
3. +Add Livemark
4. check bookmarks in livemark folder

I think all bookmarks should be imported/shown in the livemarks bookmark folder.

**Comment by evilpie** [comment]
You can edit the limit in the individual feed settings.

**Comment by Hoppaz** [comment]
Got it ... thank you so much!
