### ISSUE TITLE
"Export feeds" option should prompt to save the file

### ISSUE THREAD

**Issue by ali1234** [nt1m/livemarks#46]
Currently this option just takes you to an XML page and then you have to file -> save as which is not very user friendly. It should prompt the user to save the downloaded file instead.

**Comment by ali1234** [comment]
That's odd. It doesn't work for me. I will try disabling extensions etc.

**Comment by evilpie** [comment]
@ali1234 Is that still a problem? Is there any way we could debug this?
If you go to https://codepen.io/anon/pen/gBNzjy and click "Download me" does it open a download prompt?

**Comment by evilpie** [comment]
I bisected this fix, and I think this might have been inadvertently fixed by 
[Bug 1357487 - Turn on OOP extensions by default on Linux](https://bugzilla.mozilla.org/show_bug.cgi?id=1357487)

**Comment by nt1m** [comment]
It sounds like this is fixed now, feel free to reopen if not.
