### ISSUE TITLE
Livemarks with Firefox for Android

### ISSUE THREAD

**Issue by BaudolinO22** [nt1m/livemarks#462]
Dear all,
does Livemarks work or will it work (when) within Firefox for Android?
Thanks a lot for a kind answer.
Paolo
---
My email is baden2005@gmail.com

**Comment by evilpie** [comment]
Firefox for Android doesn't support the [bookmarks API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/bookmarks), so at least for now we won't be supporting mobile.
