### ISSUE TITLE
Change the icon colour for read posts

### ISSUE THREAD

**Issue by mate-user** [nt1m/livemarks#47]
In Firefox's Live Bookmarks, when I open a link in a new tab, the read post changes to a grey colour, and unread posts are an orange colour as shown below:

![image](https://user-images.githubusercontent.com/41811862/47307242-e09c9d00-d62e-11e8-986a-37f49352c1d6.png)

It's easier to distinguish between posts I've opened and new unopened posts.
Please bring this to Livemarks soon as Firefox 64 will remove native Live Bookmarks and this extension is the closest in user interface to Firefox's built in RSS tool.
Thanks!

**Comment by nt1m** [comment]
It's currently not possible to do with the current extension framework, but #17 plans to add something very similar.
