### ISSUE TITLE
github commit feeds no longer work

### ISSUE THREAD

**Issue by belegdol** [nt1m/livemarks#470]
https://github.com/nt1m/livemarks/commits/master.atom no longer works. According to https://news.ycombinator.com/item?id=38970403 it works with some changes: It appears you can still make it return an Atom feed if you pass the 'Accept: application/xml' header.

**Comment by tapper82** [comment]
Hi I came to report the same thing.

**Comment by Shinigamii920** [comment]
I also want to report this

**Comment by tapper82** [comment]
Ping !

**Comment by tapper82** [comment]
Hi this seems to of bin fixt on the github side. Thanks and sorry for the noise.
