### ISSUE TITLE
Github Security Lab Vulnerability Report

### ISSUE THREAD

**Issue by Kwstubbs** [nt1m/livemarks#472]
Hello, Github Security Lab has found a vulnerability in livemarks. Please enable [private-vulnerability-reporting](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) or provide a point of contact so that we can help you fix this issue.

**Comment by evilpie** [comment]
@Kwtubbs "Private vulnerability reporting" seems to be enabled.

**Comment by nt1m** [comment]
Yeah I just enabled it yesterday :)
