### ISSUE TITLE
Browing RSS link no longer adds a livemark, instead browser hangs

### ISSUE THREAD

**Issue by VilcxjoW** [nt1m/livemarks#477]
**Add-on version**
Add-on version: 3.7 (last updated 1 March 2024) running in Firefox 123.0 (64-bit) on Win10

**Describe the bug**
In Firefox, when I click on a link to an RSS feed, the page freezes or opens a blank page, and the livemark isn't added. Page Refresh button is greyed out.

**To Reproduce**
1. Go to https://www.bbc.co.uk/programmes/m001wjf8/episodes/downloads
2. Click on the link "RSS" (on the right hand side, just below the button labelled 'subscribe in sounds').
NB The URL of that link is https://podcasts.files.bbci.co.uk/m001wjf8.rss
3. The pointer changes to a hand and stays like that. The page is static - it can be scrolled up/down but none of the buttons or links on the page work. The Page Refresh button is greyed out. The feed has not been added to my list of livemarks.
NB if I open the RSS link in another browser (MS Edge) I see that it does contain XML - the first line is
(angle bracket)?xml version="1.0" encoding="UTF-8"?>(angle bracket)rss version="2.0" xmlns:media="http://search.yahoo.com/mrss/" xmlns:atom="http://www.w3.org/2005/Atom" xmlns:ppg="http://bbc.co.uk/2009/01/ppgRss" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
-- or --
1. Go to https://podbay.fm/p/inglorious-treksperts
2. Click on the link "RSS" (in the centre panel, just below the "Share" heading with its facebook/twitter/etc icons.
The URL of that link is https://anchor.fm/s/7067f3c/podcast/rss
3. A new blank page opens. It appears to be empty. The Page Refresh button is greyed out. The feed has not been added to my list of livemarks.
NB If I open the link in another browser (MS Edge) I see that it does contain XML. The first line is 
(angle bracket)?xml version="1.0" encoding="UTF-8"?>(angle bracket) rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:anchor="https://anchor.fm/xmlns">

**Expected behavior**
When I click on an RSS link, used to get the message saying that the livemark had been added to my (by default) Bookmarks folder (or whatever non-default folder I had confirgured in Options > Default folder).

**Extra context**
Workaround: Right-click on the "RSS" link > "Copy link". Go to Addons Manger and to the right of Livemarks click "..." > "Options" which should take you to a "Your Livemarks" page. Click on the "+New Livemark" button (in top right-hand corner). Paste the copied RSS link's URL into the "Enter Feed URL" box, then click on OK.

**Comment by evilpie** [comment]
Thanks for the great report.
