### ISSUE TITLE
View source is not displayed

### ISSUE THREAD

**Issue by wesinator** [nt1m/livemarks#484]
**Add-on version**
Add-on version: 3.8

**Describe the bug**
The view source button (https://github.com/nt1m/livemarks/blob/7ace8567ed1dd5d125bca12d20822bc63bf6f129/pages/subscribe/subscribe.html#L23) is not being displayed on Feeds.
Tested on Firefox 126.0.1 and Waterfox G6.0.15 on Win 10

**To Reproduce**
1. Open a RSS feed page
2. observe there is a link at the top, but no view source button is rendered

**Expected behavior**
View source display is available

[NO_TRAIN]::

**Comment by evilpie** [comment]
See #308.
