### ISSUE TITLE
Add Copy RSS link option

### ISSUE THREAD

**Issue by happysurf** [nt1m/livemarks#49]
I use your extension for extract the RSS link in a page for paste then in my Netvibes pages, for that will be great have the possibility to copy the link also for one detected RSS.
In case of two or more RSS like in the image, is easy in context menu > "copy link location" but in case of one this operation is impossible to do because nothing appear in popup.

![rss-2](https://user-images.githubusercontent.com/13637587/47424165-4ef47300-d787-11e8-9cae-e38b1d713486.png)

**Comment by evilpie** [comment]
We should at least add something to the feed preview page that makes it easier to see and copy the feed URL.

**Comment by happysurf** [comment]
I don't understand what is changed in version 1.6 about a preview, for example in this page the RSS link show the same page of 1.5:

![rss3](https://user-images.githubusercontent.com/13637587/47502546-648d9980-d868-11e8-9539-5189cb4e5af1.png)

This on Firefox 64beta3

**Comment by evilpie** [comment]
The preview is now shown when going to feed URLs directly, like https://www.tomshardware.com/feeds/rss2/all.xml. The actual preview page hasn't been changed yet.

**Comment by happysurf** [comment]
Maybe the best way is add an other blue "Copy Link" button.....

**Comment by nt1m** [comment]
Fixed by d4d4f8abacebd0fecc48f8a88fbdd1d122595cb5
