### ISSUE TITLE
problem with a feed

### ISSUE THREAD

**Issue by dianeirving** [nt1m/livemarks#490]
**Feed URL**
Please specify the feed URL: https://feeds.feedblitz.com/zooborns

**Add-on version**
Add-on version: 3.8

**Describe the bug**
Trying to add the feed takes me to a page that says "Failed to fetch feed"

**To Reproduce**
1. Go to https://feeds.feedblitz.com/zooborns
2. Click on the subscribe button
3. See error

**Expected behavior**
This should add the livemark.

**Comment by evilpie** [comment]
>XML Parsing Error: prefix not bound to a namespace
>Location: https://feeds.feedblitz.com/zooborns&x=1
>Line Number 12, Column 1: 3 zooborns&x=1:12:1
