### ISSUE TITLE
problem with a feed

### ISSUE THREAD

**Issue by dianeirving** [nt1m/livemarks#491]
**Feed URL**
Please specify the feed URL: https://www.dmagazine.com/feed/

**Add-on version**
Add-on version: 3.8

**Describe the bug**
Going to this feed just refreshes whatever is in the current tab. (Going to the feed in Google Chrome instead of Firefox shows that there is content in the feed)

**To Reproduce**
1. Go to https://www.dmagazine.com/feed/
2. See error

**Expected behavior**
This should add the livemark.

**Comment by evilpie** [comment]
The RSS feed's XML is invalid:

> XML Parsing Error: prefix not bound to a namespace
Location: https://www.dmagazine.com/feed/
Line Number 44, Column 7: 4 [feed:44:7](https://www.dmagazine.com/feed/)

​
