### ISSUE TITLE
Error with xkcd what if

### ISSUE THREAD

**Issue by Woundorf** [nt1m/livemarks#54]
Hi, I have just installed this addon as a replacement for live bookmarks and have found that the [feed for xkcd what if](https://what-if.xkcd.com/feed.atom) is not properly processed. In the browser console the following error appers when updating the feed:

> Error: Type error for parameter details (Error processing url: Expected string instead of null) for history.getVisits. background.js:130:28

**Comment by evilpie** [comment]
The Atom feed at https://what-if.xkcd.com/feed.atom doesn't have a `<link>` element for any of the feed `<entry>` elements.

**Comment by nt1m** [comment]
It's technically still a valid feed :(

`xmlns:ns` is set to http://www.w3.org/2005/Atom, which means `ns:href` or `ns:rel` are the correct attribute names for this.

I guess the feed parser could look for all the xmlns attributes that are set to http://www.w3.org/2005/Atom, and take that namespace into account. The other possibility would be to strip out all the namespaces from the document.

**Comment by nt1m** [comment]
The easiest solution of course would be for XKCD to make their feed more conventional...
