### ISSUE TITLE
OPML export produces broken file

### ISSUE THREAD

**Issue by Denny-89** [nt1m/livemarks#6]
Hey, here's the OPML file you requested (zipped because Github doesn't allow xml) - [livemarks-opml.zip](https://github.com/nt1m/livemarks/files/2242967/livemarks-opml.zip)

How to reproduce the "No feeds found" error:
1. Export via Livemarks
2. Delete all live bookmarks
2. Try to import the previously exported file via Livemarks

I don't know if it's important or not - i'm using Firefox 62.0b12 64-bit with e10s enabled

**Comment by nt1m** [comment]
Thanks! I'll look into it.

**Comment by nt1m** [comment]
The OPML you shared seems to have some extra `,` characters before the `<outline` opening tags.

I've double checked the code, and I don't see any possible line that could add those characters.  Have you edited the OPML ?

**Comment by Denny-89** [comment]
Nah, i didn't edit anything. Here's another one i exported right now and it gives me the same error - 
[livemarks-opml.zip](https://github.com/nt1m/livemarks/files/2243309/livemarks-opml.zip)

**Comment by nt1m** [comment]
@Denny-89 It was an issue with the export code which was producing broken OPML. It should be fixed in the next update. Thanks for reporting!

**Comment by nt1m** [comment]
@Denny-89 I've published a new update fixing this: https://addons.mozilla.org/firefox/addon/livemarks/versions/

Let me know if it works for you :) Thanks again!

**Comment by Denny-89** [comment]
I tried and first it wouldn't work, but then i looked at the xml file and noticed Next-Episode's feed url is the only one looking different than others. After i removed the whole outline tag for that site and tried to import again, everything worked.

Their url syntax is:
https://next-episode.net/watchlist.xml?user=USERNAME&k=XXX
XXX = 32-character alphanumeric string

Since such feeds are in the minority and rarely encountered so i believe the issue is fixed.

btw: at importing, the default folder setting (in my case Bookmarks Toolbar) gets ignored and it puts everything into Other Bookmarks.

**Comment by nt1m** [comment]
Interesting, the `&` character is causing issues. Filed #18.
