### ISSUE TITLE
Option to disable feed preview

### ISSUE THREAD

**Issue by Brawl345** [nt1m/livemarks#62]
Can you please add an option to disable the feed preview? I really like LiveMarks, but would like to use another add-on for feed previews (when visting the feed directly).

**Comment by nt1m** [comment]
@Brawl345 Adding an option is feasible and seems like a good idea.

However, I'm curious, what features are missing in the feed preview functionality that makes you want to use a different add-on ?

**Comment by Brawl345** [comment]
It's for example not possible to show the XML via CTRL+U because LiveMarks redirects to it's own site while e.g. this add-on: https://addons.mozilla.org/de/firefox/addon/feed-preview/ loads it in another way that makes it possible to see the XML.

It might be also be a good idea for the future when there are more feed preview add-ons for e.g. subscribing directly via another feed reader.
