### ISSUE TITLE
slowness viewing xml files

### ISSUE THREAD

**Issue by rbro** [nt1m/livemarks#69]
I noticed that when Livemarks is enabled, I can't view xml files in Firefox, or if I can, they render very slowly.  If I disable Livemarks, the xml files appear instantly.

As an example, if I go to https://www.w3schools.com/xml/note.xml with Livemarks enabled, the file takes a long time to render.

Please let me know if I can supply any more information to help reproduce it.  Thanks.

**Comment by evilpie** [comment]
Good catch, fixed with 054fafcec8c7f87aa17773f2bd592c84f9050b25
