### ISSUE TITLE
[Question] Why use an iframe in feed preview?

### ISSUE THREAD

**Issue by charakterziffer** [nt1m/livemarks#74]
The feed preview consist out of a header and an iframe with the actual feed content. Because of the iframe this content can’t be user styled (e.g. make the item_title smaller) and I have to use the tab key several times or click into the iframe before I can scroll it with my keyboard.

What’s the reasoning behind the extra iframe for the feed contents? Are there security reasons? Is it a necessity for parsing the feed? I’d personally prefer to have only one page for the feed preview not a page inside a page. It’d make the content more accessible for me.

**Comment by nt1m** [comment]
The sandboxed iframe is there for security reasons, it’s the only way to ensure no script that might potentially be contained in a feed gets executed. I agree it’s not ideal for styling though or accessibility though.

We might be able to mitigate this by putting extra accessibility attributes and with a custom css feature however.

**Comment by charakterziffer** [comment]
Thank you very much! You are doing great work and I’m glad I still can use dynamic bookmarks for RSS feeds in Firefox.
