### ISSUE TITLE
Version 1.8

### ISSUE THREAD

**Issue by thexile** [nt1m/livemarks#77]
Version 1.8 deleted all my feeds.

Options is not working (cannot re-import .opml) and feeds cannot be added.

Reverted back to version 1.7.

**Comment by nt1m** [comment]
@thexile Do you have any errors in the console ?

**Comment by nt1m** [comment]
@thexile Also, which Firefox version are you using ? The latest version of the add-on is supposed to migrate the local storage to sync storage, to make Firefox sync work properly.

**Comment by thexile** [comment]
I am using Firefox 63.0.3 and 64,0b10.

**Comment by eikaramba** [comment]
unfortunately same for me too.

**Comment by juarezr** [comment]
**Livemarks 1.8 (nov 19) with FF 64.0b10 trashes memory and disk.**
Beginning yesterday, firefox started to consome all memory in the computer.
Firefox memory on Win10 does not stop growing. Also when closing ff disk writing goes to 100% in Task Manager.
When Sync is disconnected, the memory behaviour works normally.

**Comment by juarezr** [comment]
Livemarks used while noticed the high memory usage and sync forever bug.

**Comment by eikaramba** [comment]
yes it is definetly livemarks. so i debugged it while the issue happened and somehow the storage get method is called resp. also a listener is created all the time.
![grafik](https://user-images.githubusercontent.com/1320525/48782097-b7c70080-ecdd-11e8-97fa-bb5b80465c20.png)

**Comment by nt1m** [comment]
@eikaramba Thanks for looking into this! 
@evilpie I'm not good at debugging performance issues. Do you think it would be possible to optimize the onChanged listener ?

**Comment by evilpie** [comment]
I suggest we first revert this change. That means we have to add downgrade code. Then we figure out why we are putting so much stuff into storage.

**Comment by evilpie** [comment]
At least `updated` changes with every feed update, multiplied by the number of feeds.

**Comment by Gristrosia** [comment]
I also reverted to 1.7.

The new version 1.8 hogs Firefox like crazy and I can't access the options for the addon anymore. Clicking on options redirects to the add a new livemark page, clicking on the Option button does nothing. 


![capture](https://user-images.githubusercontent.com/25066224/48810501-0bf7d200-ed2a-11e8-8ef8-58e717d04a1c.JPG)

**Comment by LoneBoco** [comment]
This might be related to my old bug #26.  If you have an invalid bookmark in your Livemarks store somehow the whole addon breaks.  I'm not sure how to clear it out.  I've tried uninstalling Livemarks and restarting Firefox but it isn't clearing out the bad data.

**Comment by TomCP** [comment]
Confirmed also from my side, Firefox64 (v64, downgraded also to 63 and 62 with no change) started to eat my CPU resources like hell, all the time 15-30% or 100% on one of four CPUs, I found thread TargetedStockObject64. No reset or FF reinstall didn't help.
After disabling Livemarks, everything is fine now.
Likely this is connected with LM 18 upgrade few days ago, I didn't notice this before.

**Comment by evilpie** [comment]
@nt1m how did you provide this test version? It would be good to have some users check that the storage migration is working for them as well.

**Comment by evilpie** [comment]
I released version 1.9 without sync support now, please @TomCP  @LoneBoco @thexile @eikaramba tell me if this fixes the issue for your. Your previous feeds should have been preserved.

**Comment by eikaramba** [comment]
good news everyone - installed 1.9 over 1.8 and migration from sync->local storage worked. after 20 minutes i don't see the ressource usage problem coming up again. **Should be fine for now.**
thanks for the quick response. Let us know if we can help somehow finding the culprit of the sync issue by testing development versions or give you more debug hints (ideally you are able to reproduce it yourself in some VM with a fake sync account or so).

The good here is that after everything i have done already, the ids of the bookmark folders actually stayed the same. So at least we know that one can rely on them being stable.

**Comment by evilpie** [comment]
Thanks @TomCP for your feedback.

Apparently this also caused #80.

**Comment by evilpie** [comment]
Closing this now, #22 is going to stay open when we decide to implement sync again.
