### ISSUE TITLE
Unusable (performances, features): back to Firefox 63.0.3

### ISSUE THREAD

**Issue by TroudhuK** [nt1m/livemarks#85]
Hi,

You have the heavy task to develop the [almost official replacement](https://addons.mozilla.org/fr/firefox/collections/mozilla/refined-reading/) for live bookmarks, because Firefox don't understand that the users of this feature are the same who disable all the spying functions to send usage reports.

I just tried the update to Firefox 64 + Livemarks: catastrophic.
- huge CPU usage, freezes all, far top in about:performances
- not the same icons, uses the favicon instead of ![livemark-folder](https://user-images.githubusercontent.com/11449740/49869180-ea14db00-fe0f-11e8-9119-260ffd30f658.png) ![livemark-item](https://user-images.githubusercontent.com/11449740/49869183-ec773500-fe0f-11e8-963e-c23b81cbbf42.png) (with the read/unread features bases on history)
- creates true bookmarks instead of just a "live" one (and the rss entries must be only in RAM)
- no on-demand refresh feature when we just deploy the "folder", we have to right-click
- useless periodic refresh feature (we don't care about refreshing something we don't look at)
- duplicated entries, I had 3 or 4 times the same for some feeds, I think it's the periodic refresh which does that (a manual one clean duplicated entries)
- when performances are very bad, I couldn't open the options popup, it appears and disappears, or doesn't react so I couldn't try other settings

=> disabled and back to Firefox 63.0.3, read live bookmarks reinstalled.

Maybe a conflict with an other addon, maybe a problem with the fact I use 2 windows (but the second doesn't have a personal bar), or currently 120 tabs. It's not your fault, Mozilla is the only one responsible, torpedoing its own product.

Hoping to one day have a real live bookmarks revival/replacement to update Firefox.

**Comment by nt1m** [comment]
Sorry to hear you had a bad experience with the add-on :/

> huge CPU usage, freezes all, far top in about:performances

Tracked in #61

> not the same icons, uses the favicon instead of livemark-folder livemark-item (with the read/unread features bases on history)

Not possible with the current extension APIs unfortunately.
Unread/read indicator is tracked in #17, although this will not help with CPU usage when/if implemented...

> creates true bookmarks instead of just a "live" one

> (and the rss entries must be only in RAM)

The livemark list is in RAM, but not the RSS entries themselves.

> no on-demand refresh feature when we just deploy the "folder", we have to right-click

This isn't possible with the current extension APIs, you can vote for this API request: https://bugzilla.mozilla.org/show_bug.cgi?id=1448518

> duplicated entries, I had 3 or 4 times the same for some feeds, I think it's the periodic refresh which does that (a manual one clean duplicated entries)

Going to file a separate issue for that, thanks for reporting.

**Comment by TroudhuK** [comment]
Thanks and sorry for this bad usage of issue creation.

**Comment by mdcdr** [comment]
I have similar problem. Firefox is extremely slow and unusable after adding feeds, it take 30 or more seconds to respond to click, and memory consumption is 1.5G and increasing until I close it.
Also there is a lot of network traffic it seems constantly 100-300Mbit until I close Firefox.
Like it's in some kind of loop, constantly downloading something.
I also tried to manually add feeds, and after adding 5 or 6 feeds sometimes even 7, it starts eating memory and downloading something and Firefox is unusable.

**Comment by evilpie** [comment]
I think we don't need this issue anymore. Most of the problems have their own issues and the performance problem was hopefully fixed now.
