### ISSUE TITLE
Livemarks can't load Reddit rss feeds 

### ISSUE THREAD

**Issue by uhrheber** [nt1m/livemarks#89]
A feed like https://www.reddit.com/r/news/.rss can be opened in Firefox and used as live bookmark (I'm still on 63), but Livemarks says "Failed to fetch feed" on all Reddit feeds.

When adding the feed manually, I get a popup that shows "Error: 0:".

**Comment by nt1m** [comment]
See #38, you need to whitelist reddit from tracking protection.
