### ISSUE TITLE
Rework livemark store mechanism

### ISSUE THREAD

**Issue by nt1m** [nt1m/livemarks#94]
It sounds to me that the onChanged listener is causing trouble here. Getting rid of it would probably help with memory/CPU/crash issues.

Here's a proposed list of changes:
- [ ] Remove strange StoredMap data structure and just inline all that code into LivemarkStore
- [ ] Possibly centralize storage writes to only one thread (background page), but allow reads from any thread. So change events would only come from background page
 
@evilpie What do you think ? Can you think of any other changes to make ?

**Comment by evilpie** [comment]
I think most importantly if we ever want to re-enable sync, is that we somehow prevent write->change event->write cycles. Where outside the background page do we access storage? Do you mean the settings page.

**Comment by nt1m** [comment]
@evilpie We read storage on the settings page + the background page. We write to storage from the settings page and from the reader page (Add Livemark button).

**Comment by nt1m** [comment]
I think one thing that may be worth doing is simply use runtime messaging instead of the onChange listener. Since every part of the UI knows when it changes storage, they can just send an explicit message, instead of having the other side wait for a onChange listener.
