### ISSUE TITLE
View Source shows the current HTML source instead the feed source code

### ISSUE THREAD

**Issue by etruel** [nt1m/livemarks#96]
I'm in Debian Linux.  The addon is great and works well.  I've got only this issue:

**I've tested a feed and I get :**
![image](https://user-images.githubusercontent.com/3663229/50010945-8b7b6880-ff99-11e8-8eeb-e907a287c9c5.png)

**By clicking view source link shows me the following :**
URL = view-source:moz-extension://7c1143f2-1f89-4a0e-b334-6f22bc7e89ae/pages/subscribe/subscribe.html?https%3A//etruel.com/feed/

![image](https://user-images.githubusercontent.com/3663229/50010767-085a1280-ff99-11e8-9de6-734cd73cd304.png)

**Seems to show me the feed reader source instead of the feed source.**

Thanks for the great job!

**Comment by freaktechnik** [comment]
This seems to be back for me (unless this fix hasn't been published yet)
