### ISSUE TITLE
Livemarks also not appearing in Bookmarks Toolbar

### ISSUE THREAD

**Issue by thecbrooks** [nt1m/livemarks#98]
Just signed up and set it up to load on the bookmarks toolbar to replace my live bookmarks, which died when I updated. But it's not appearing.
I used the opml file to set it up...I tried to attach it here but got a flag that that file type isn't supported here..

**Comment by thecbrooks** [comment]
So, it looks like I have to toggle each one to the bookmarks toolbar from each feed...that ended up working.

**Comment by nt1m** [comment]
Yes, you need to toggle each of the feed. There's the "default folder" setting that should apply to newly imported bookmarks too, if it doesn't, please let me know.

**Comment by prouss1** [comment]
Sorry to be dumb but I'm missing how this is supposed to work.  I've imported the opml file that Firefox created but I don't see a livemark folder anywhere and I'm not sure what you mean by "toggle each one to the bookmarks toolbar from each feed".  Thanks!
